curl -O https://extdist.wmflabs.org/dist/extensions/3D-master-0de38a2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AControlImageLink-master-61ce1d3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AJAXPoll-master-5b1a66a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AbsenteeLandlord-master-4eba21d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AbuseFilter-master-7a6e063.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AbuseFilterBypass-master-4837809.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AccessControl-master-26337d7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AccountInfo-master-a014977.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Acrolinx-master-bef47b6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ActiveAbstract-master-85749a8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AdManager-master-e50227c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AddHTMLMetaAndTitle-master-44283c9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AddMessages-master-c002cf6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AddPersonalUrls-master-21eac9d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AddThis-master-27d826a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AdminLinks-master-d928f24.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AdvancedMeta-master-f416f43.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AdvancedSearch-master-665ea78.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AjaxShowEditors-master-f1e9f51.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AkismetKlik-master-ccc3932.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AllTimeZones-master-e313897.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AnchorHandler-master-8498664.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AnonPrivacy-master-1105e7c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AntiSpoof-master-90f1cc9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ApiFeatureUsage-master-9064ee2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ApprovedRevs-master-d0b3590.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Arrays-master-a29815c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ArticleCreationWorkflow-master-1c5825f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ArticleFeedbackv5-master-dca0d35.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ArticleIndex-master-2b1ce4c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ArticleMetaDescription-master-c56e9a2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ArticlePlaceholder-master-b900af6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ArticleRatings-master-8d1c237.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ArticleToCategory2-master-3867b0f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Athena-master-4668910.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Auth_remoteuser-master-840c302.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AuthorProtect-master-c708d9a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AutoCategoriseUploads-master-8021f3a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AutoCreateCategoryPages-master-8a48985.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AutoGallery-master-c5525bf.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/AutoProxyBlock-master-06f568a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Awesomeness-master-679ce06.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Babel-master-ec99765.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BaseHooks-master-e5173bf.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BatchUserRights-master-779da6c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BetaFeatures-master-74ec050.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BibManager-master-6745b11.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BiblioPlus-master-30f2a5c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Blackout-master-db9b2f7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlockAndNuke-master-6fd2d64.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlockInactive-master-70f28f5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlogPage-master-22e2baf.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceAbout-master-ca710f7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceArticleInfo-master-99a4df0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceArticlePreviewCapture-master-7f3c2b8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceAuthors-master-de28cea.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceAvatars-master-8a880f7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceBookshelf-master-f7dced8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceCategoryCheck-master-df50444.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceCategoryManager-master-49e9c1e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceChecklist-master-447eb6c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceConfigManager-master-7ab3ca8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceContextMenu-master-38148a9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceCountThings-master-d476b91.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceCustomMenu-master-815bc93.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceDashboards-master-fc8bbeb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceDistributionConnector-master-0e0b5db.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceEchoConnector-master-3debabe.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceEmoticons-master-ae10027.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceExpiry-master-7a5895c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceExportTables-master-ca777f1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceExtendedFilelist-master-a6b6182.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceExtendedSearch-master-5e3d343.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceExtendedStatistics-master-b501366.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceFilterableTables-master-0acd3ec.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceFlaggedRevsConnector-master-d3d24f8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceFoundation-master-45e3f81.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceGroupManager-master-1fea36c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceHideTitle-master-1a82600.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceInsertCategory-master-ccff15e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceInsertFile-master-6d34121.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceInsertLink-master-bf45965.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceInsertMagic-master-4477161.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceInsertTemplate-master-2fdb60b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceInterWikiLinks-master-3d1cc21.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceMultiUpload-master-0ff9485.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceNSFileRepoConnector-master-748d9b9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceNamespaceCSS-master-08c0561.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceNamespaceManager-master-20a188b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpicePageAccess-master-2d81bd0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpicePageAssignments-master-cbebba8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpicePageFormsConnector-master-583372f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpicePageTemplates-master-647e0ae.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpicePageVersion-master-39eb963.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpicePagesVisited-master-6bb075b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpicePermissionManager-master-96d799f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpicePlayer-master-e7830d5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpicePrivacy-master-0b8992d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceProDistributionConnector-master-8822439.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceQrCode-master-d0a29f4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceRSSFeeder-master-d6690ae.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceRating-master-cde7574.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceReadConfirmation-master-1054b10.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceReaders-master-a3ef375.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceReminder-master-b0ccd81.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSMWConnector-master-8645c7a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSaferEdit-master-7470310.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSignHere-master-954a4f9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSmartList-master-3ca9438.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSocial-master-eb0a32f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSocialArticleActions-master-df06ce1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSocialBlog-master-5c6eb0f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSocialComments-master-eab9c2b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSocialMicroBlog-master-868a4d9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSocialProfile-master-fb0b96f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSocialRating-master-63ebeb9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSocialResolve-master-082456e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSocialTags-master-9a7fc4d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSocialTimelineUpdate-master-2a5dbeb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSocialTopics-master-7fd16f7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSocialWatch-master-53dc343.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSocialWikiPage-master-c89c6ee.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceSubPageTree-master-fb4e43b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceTagCloud-master-15a22bc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceUEModuleBookPDF-master-d9cac9a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceUEModuleDOCX-master-5519ead.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceUEModuleHTML-master-0a93499.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceUEModulePDF-master-5bb3761.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceUEModulePDFRecursive-master-d30a57d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceUEModulePDFSubpages-master-f270dff.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceUEModuleTable2Excel-master-b0db7c9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceUniversalExport-master-85d6191.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceUsageTracker-master-31fa174.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceUserInfo-master-fafc729.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceUserManager-master-3b06a60.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceUserSidebar-master-eb6c7c2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceVisualDiff-master-a92cac4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceVisualEditorConnector-master-950cbbc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceWatchList-master-5bfee33.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceWhoIsOnline-master-f97eea2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BlueSpiceWikiExplorer-master-f7a7e2f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BoilerPlate-master-e1a4049.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BounceHandler-master-d09f83e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BreadCrumbs-master-a3a7950.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BreadCrumbs2-master-400dbad.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/BrickipediaExtra-master-498c1d8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Buggy-master-adff480.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CIForms-master-653ee1a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CSS-master-a8cafdb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Calendar-master-0b7234a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CampaignEvents-master-c72065e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Campaigns-master-a35f17e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Capiunto-master-21befed.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Cargo-master-95f5d16.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Carp-master-848f61a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CatTalk-master-82716f3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CategoryExplorer-master-381b75e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CategoryLockdown-master-fea6b04.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CategorySortHeaders-master-0db2e22.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CategoryTagSorter-master-bd5f0a0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CategoryTests-master-c466ee2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CategoryTree-master-02fbb97.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CategoryWatch-master-dbf53e0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CentralAuth-master-4005287.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CentralLogging-master-608b968.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CentralNotice-master-088aaf5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Challenge-master-d0b4551.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ChangeAuthor-master-b31ad8d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ChangeUserPasswords-master-851440a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CharInsert-master-254a358.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CharRangeSpan-master-e295f12.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CheckUser-master-6da53df.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Checkpoint-master-c7ebbd4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ChessBrowser-master-08db5d8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CirrusSearch-master-155d5a1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Cite-master-d9b2934.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CiteDrawer-master-2b492e8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CiteThisPage-master-3579299.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Citoid-master-6cfccf2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CleanChanges-master-4245d3e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CloneDiff-master-107cf49.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CloseWikis-master-a6decda.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CodeEditor-master-4388be6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CodeMirror-master-10958bc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CodeReview-master-4df23fc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Cognate-master-0895b90.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CognitiveProcessDesigner-master-a9d9380.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CollaborationKit-master-6b09c6a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CollapsibleSections-master-3478a10.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CollapsibleVector-master-acede0a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Collection-master-25bf4aa.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CommentStreams-master-1d55fd5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Commentbox-master-e78f760.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Comments-master-c24eb8c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CommonMessages-master-3165956.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CommonsMetadata-master-e53d2d6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ConfigManager-master-7f7b5c1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ConfirmAccount-master-bd447a3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ConfirmEdit-master-2b96847.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CongressLookup-master-94c22fb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ContactPage-master-d884bf8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ContentTransfer-master-fc13df8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ContentTranslation-master-3fedca9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ContributionCredits-master-ef11d1f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ContributionScores-master-d4dae78.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ContributionsList-master-47b3523.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Contributors-master-9d3e401.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CookieWarning-master-62d577a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CosmosProfile-master-6879348.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CountDownClock-master-ed06b66.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CrawlableAllPages-master-291fd3d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CreateAPage-master-701a046.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CreatePage-master-b249049.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CreatePageUw-master-56307d8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CreateRedirect-master-3edca49.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CreateUserPage-master-f797551.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CreatedPagesList-master-2591c84.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/CreditsSource-master-627b2b3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DPLforum-master-7f58825.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DarkMode-master-2c6c85b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Dashiki-master-f80dd32.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DataTable2-master-e6091ec.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DataTransfer-master-81be09e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DateDiff-master-1168d08.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DebateTree-master-a447f56.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DebugMode-master-2afe90f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DebugTemplates-master-cadad0b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DeleteBatch-master-de43801.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DeleteOwn-master-7e58c60.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DeletePagesForGood-master-5515eec.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DeleteUserPages-master-20d3bd7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Description2-master-4ba5e24.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DeviceMapLogCapture-master-b038a2f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Diagnosis-master-d3da7df.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DidYouKnow-master-5a73439.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DisableAccount-master-fb1cab2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Disambiguator-master-822429b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Discourse-master-41b5baf.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DiscussionThreading-master-c9de08e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DiscussionTools-master-d3a44b1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DismissableSiteNotice-master-839125e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DisplayTitle-master-47ee9cc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DisqusTag-master-2fb96c6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DocBookExport-master-30c7343.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DonationInterface-master-f8b4856.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DoubleWiki-master-2dc4da3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DownloadCounter-master-aab5059.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Drafts-master-d858fa5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DrawioEditor-master-4b2ae7b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DumpsOnDemand-master-83543aa.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Duplicator-master-53c629d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DynamicPageList-master-8391e73.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DynamicPageListEngine-master-190ce1a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/DynamicSidebar-master-2bf5bc0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EasyWiki-master-cea1b26.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Echo-master-6430eab.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EditAccount-master-6067870.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EditNotify-master-a06f9c0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EditSimilar-master-ac20b66.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EditSubpages-master-b046c0d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EditUser-master-92a4fd0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Editcount-master-54a6f3a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EditcountAdditions-master-b6f3280.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Elastica-master-0a677c0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ElectronPdfService-master-90dffd3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EmailAuth-master-08b0156.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EmailAuthorization-master-a9d746e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EmailCapture-master-9453ee7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EmailDeletedPages-master-96767e8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EmailDiff-master-48d053e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EmergencyCaptcha-master-690c204.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EncryptedUploads-master-6a983ed.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EnhanceContactForm-master-e0225bf.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EnhancedUpload-master-886a77c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EntitySchema-master-70addd0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ErrorHandler-master-4cc0255.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EtherpadLite-master-4e5e2f5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EventBus-master-ac9c0a4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EventLogging-master-faaad63.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EventSimulator-master-685af0f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/EventStreamConfig-master-24e6bc6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Expressions-master-138cf23.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ExtJSBase-master-022d5d6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ExtensionDistributor-master-ef0a958.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ExternalArticles-master-d9b3b4e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ExternalData-master-c2e8027.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ExternalGuidance-master-d1b2453.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ExternalLinkConfirm-master-1cd6a48.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ExtraLanguageLink-master-4f3983d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FanBoxes-master-fcc8a4c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Farmer-master-f5b27ab.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Favorites-master-621a884.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FeaturedFeeds-master-8dd3148.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Figures-master-7c4b7f5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FileAnnotations-master-b18ffb2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FileExporter-master-4d600dc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FileImporter-master-b6f570a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FileSystemImageServer-master-f1c4eea.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FilterListUsers-master-adab9db.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FilterSpecialPages-master-3bfbbb2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FixedHeaderTable-master-bfaa598.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FlaggedRevs-master-e2abe38.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FlexDiagrams-master-50d191a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FlexiSkin-master-c495873.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FlickrAPI-master-f2a22d0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Flow-master-0a212de.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ForcePreview-master-fc00811.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Form-master-522a77a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FormWizard-master-569fc94.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FormatDates-master-5af89c8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Forms-master-0ec6c46.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FundraiserLandingPage-master-28451bc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FundraisingEmailUnsubscribe-master-b8934b9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/FundraisingTranslateWorkflow-master-6930dd8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GPGMail-master-0b1a075.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GWToolset-master-7196fb5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Gadgets-master-e766f9d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Genealogy-master-f067326.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GenerateMochaConfig-master-efe54dc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GeoCrumbs-master-8c974b1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GeoData-master-56bf9dc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GeoGebra-master-b25600d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GettingStarted-master-58c05c4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Git2Pages-master-1d40b65.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GitGadgets-master-992e9d6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Gitweb-master-91834c3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GlobalBlocking-master-f2d5f6e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GlobalCheckUser-master-648afd4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GlobalContribs-master-70fc7be.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GlobalContributions-master-67ace0d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GlobalCssJs-master-4f4d945.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GlobalNotice-master-cfcde16.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GlobalPreferences-master-57c6b4b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GlobalUsage-master-74ae596.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GlobalUserGroups-master-97824cd.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GlobalUserPage-master-7597f8a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GlobalUserrights-master-78925e6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GlobalWatchlist-master-bfde88a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GoToShell-master-e44ecfe.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GoogleAdSense-master-cc091cd.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GoogleAnalyticsMetrics-master-8e030b7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GoogleAnalyticsTopPages-master-99d09d5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GoogleAuthenticator-master-70a5522.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GoogleCustomWikiSearch-master-7f429a6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GoogleDocCreator-master-6b78649.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GoogleDocTag-master-dde7669.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GoogleDocs4MW-master-b917a70.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GoogleGeocode-master-9c84e06.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GoogleLogin-master-4bc4ceb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GoogleNewsSitemap-master-d2c60df.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GooglePlaces-master-f8f67c7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GoogleSiteSearch-master-3c3e732.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Graph-master-33ed60b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GraphQL-master-50cb1b3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GraphViz-master-aa52b5b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Gravatar-master-d51d4bf.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GroupWhitelist-master-ba52c11.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GroupsSidebar-master-4920faf.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GrowthExperiments-master-4b03425.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/GuidedTour-master-f09f435.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HAWelcome-master-227e60e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HSTS-master-6c16287.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HTMLPurifier-master-f0d4381.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HTMLTags-master-ed7d604.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HTMLets-master-d231207.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HashTables-master-8f52017.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HeadScript-master-3377daf.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HeaderTabs-master-fda8b1d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HelpCommons-master-2e2b505.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HelpPages-master-485ac1d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HidePrefix-master-8002be0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HierarchyBuilder-master-a5e9e32.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HighlightjsIntegration-master-976b4bf.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HitCounters-master-820c4f0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HostStats-master-2d17d74.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/HoverGallery-master-eee681c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Hreflang-master-607385f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Html2Wiki-master-abc787f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/I18nTags-master-6b329c6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/IPInfo-master-e25c22f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Ids-master-5afbcc3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/IframePage-master-7eeb186.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ImageCompare-master-6c2abd4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ImageMap-master-1052064.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ImageRating-master-42c769d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ImageSuggestions-master-e790c55.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ImageTweaks-master-0a0e3cc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ImapAuthorization-master-da9e1ef.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ImportArticles-master-2000621.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ImportFreeImages-master-b60d8f1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ImportOfficeFiles-master-93e13d0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ImportUsers-master-7150303.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Inbox-master-48a8870.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/IndexFunction-master-5e7a5a7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/InlineCategorizer-master-bbf3f3a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/InputBox-master-3871f95.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Insider-master-9339079.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/InteractiveBlockMessage-master-221b58e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Interlanguage-master-7518732.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Interwiki-master-1cfcab7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/InterwikiExtracts-master-d28dab1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/InterwikiSorting-master-97381c8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/InviteSignup-master-e3ca8c0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/JSBreadCrumbs-master-a649416.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Josa-master-33772f1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Json5Config-master-51e41e8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/JsonConfig-master-5cdc2ea.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/JsonData-master-c42ae07.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Kartographer-master-8648c84.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LDAPAuthentication2-master-7402080.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LDAPAuthorization-master-62afc75.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LDAPGroups-master-a65a4c2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LDAPProvider-master-4e02428.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LDAPSyncAll-master-a66a3ff.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LDAPUserInfo-master-1e54026.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LabeledSectionTransclusion-master-b53bf48.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LandingCheck-master-071e2df.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LanguageSelector-master-ba32e1c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LanguageTag-master-cce68df.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LanguageTool-master-a5a1f51.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LastModified-master-c7ab811.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LastUserLogin-master-316e9af.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LdapAuthentication-master-fac0f70.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LegalLogin-master-5ef5cf1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LibraryCheckout-master-6472282.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Lingo-master-9e6b62e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LinkFilter-master-1adcf86.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LinkSuggest-master-2b6022d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LinkSuggest2-master-38132c2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LinkTarget-master-1e94041.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Link_Attributes-master-5943b83.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LinkedWiki-master-1d78dca.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Linter-master-a52faf1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LiquidThreads-master-6a3746b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Listings-master-af8a6ad.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LiveChat-master-e1e4e66.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LiveStreaming-master-9c88f40.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LocalisationUpdate-master-04430ba.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LockAuthor-master-bde65b9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LockDownEnglishPages-master-1da82a3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Lockdown-master-f8d5f01.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LogEntry-master-f779cf9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LoginNotify-master-f1610a3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LogoFunctions-master-3a78974.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LookupUser-master-2e861ce.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/LoopFunctions-master-358ec9a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Loops-master-085314f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MP3MediaHandler-master-47c890d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MWVersionInfo-master-5eb11ea.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MachineVision-master-8d154d6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MadLib-master-0f9ef15.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MagicNoCache-master-d5c28d6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MagicNumberedHeadings-master-f4c0dcd.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Mailgun-master-7d49e5d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Maintenance-master-6e2042f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MaintenanceShell-master-16180b6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MapSources-master-6d2b5d5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MarkAsHelpful-master-777abd4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MassEditRegex-master-dca9c4d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MassMessage-master-7c9d015.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MassMessageEmail-master-d53f298.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Math-master-783797b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MathSearch-master-a3f53cc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MediaFunctions-master-1ba77c8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MediaModeration-master-cc8b5eb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MediaSearch-master-ab8c6f1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MediaUploader-master-9e505fb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MediaWikiChat-master-4bfdfe8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MediaWikiFarm-master-b7b64f1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Memento-master-f93b39f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MenuEditor-master-d31aab1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MergeArticles-master-1e10902.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MessageCommons-master-d9789dd.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MetaMaster-master-4a26f3c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Metadata-master-d100fc3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MiniInvite-master-198850d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MinimumNameLength-master-6e30840.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MintyDocs-master-935a607.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MissedPages-master-2cb2156.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MixedNamespaceSearchSuggestions-master-dbc8b76.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MobileApp-master-c9c44ba.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MobileDetect-master-0f5f119.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MobileFrontend-master-230d13a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MobileFrontendContentProvider-master-4321fd9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Model-master-144ef54.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MolHandler-master-3a159aa.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Monstranto-master-e4b9b9a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MontserratFont-master-fedb189.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Mpdf-master-1c1a5a4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MsCalendar-master-74c2477.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MsCatSelect-master-e39509e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MsInsert-master-5d52a7c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MsLinks-master-7ff0ed2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MsUpload-master-4e4910f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MsWikiEditor-master-ef148a8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MultiBoilerplate-master-46225df.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MultiLanguageManager-master-87aa580.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MultiMail-master-7362690.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MultiMaps-master-d9bb2d4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MultimediaPlayer-master-7a8a4ca.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MultimediaViewer-master-785352e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MusicBrainzAuth-master-29cd4c5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/MyVariables-master-a6d90e9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NCBITaxonomyLookup-master-d2dc57e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NSFileRepo-master-070d2b7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NamespaceHTML-master-294ddbf.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NamespacePaths-master-0cda26d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NamespacePopups-master-631116a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NamespaceRelations-master-44ed5f2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NamespaceSidebar-master-3b6ee46.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NativeSvgHandler-master-8544776.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NaturalLanguageList-master-b6daa85.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NavigationTiming-master-a4bd8ac.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NearbyPages-master-a0fd970.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Negref-master-754ff32.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NetworkAuth-master-5c02c62.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NewSignupPage-master-e98606b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NewUserActions-master-19cddc1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NewUserMessage-master-440a38f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NewUserNotif-master-c0df125.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NewestPages-master-3ae69a0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/News-master-27673a3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NewsBox-master-b565563.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NewsTicker-master-f7bb493.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Newsletter-master-8b91c25.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NoBogusUserpages-master-7a480d0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NoCat-master-4fa5943.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NoTitle-master-1ed2e6f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NotebookViewer-master-e9e30cd.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NotesLink-master-09783b1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Nuke-master-435fb5d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NukeDPL-master-4506e17.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NumberFormat-master-b7ae02d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NumberOfWikis-master-e484cbb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Numbertext-master-6736f54.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/NumerAlpha-master-1d85e1a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OATHAuth-master-33b5f93.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OAuth-master-9f8d4d9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OAuthAuthentication-master-4f1ef55.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OAuthRateLimiter-master-9f2f28c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OOJSPlus-master-61dd53b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OOJsUIAjaxLogin-master-0e9bdbc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ORES-master-ef425dc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OdbcDatabase-master-f752834.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OfflineImportLexicon-master-e29e421.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OnionsPorFavor-master-1d981ad.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OnlineStatus-master-c12e43e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OnlineStatusBar-master-22ed089.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OnlyRecentRecentChanges-master-cd91f13.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OpenBadges-master-b26f91c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OpenGraphMeta-master-b245d26.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OpenID-master-971d249.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OpenIDConnect-master-3416e02.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OpenJsCad-master-5c426c8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OpenLayers-master-9b01f16.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OpenStackManager-master-9aaaa7e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OrphanedTalkPages-master-63d89ff.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/OurWorldInData-master-47fe548.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PCRGUIInserts-master-f95ab2b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PGFTikZ-master-a3f0f52.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageAssessments-master-80ca7a6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageAuthors-master-1a17493.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageCheckout-master-a450fbc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageCreationNotif-master-6e74b07.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageDisqus-master-41c6cf0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageExchange-master-52cc36c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageForms-master-1b18d2c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageImages-master-fca29f3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageInCat-master-9923328.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageLanguage-master-6ca35b7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageMagic-master-aa162eb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageNameFormula-master-cb25c88.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageNotice-master-ec7e625.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageOwnership-master-a43aefb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PagePermissions-master-b50bc36.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PagePopups-master-bf36672.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PagePort-master-51a36dd.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageProperties-master-cab9766.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageSchemas-master-8b7facf.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageTools-master-ac8ec62.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageTriage-master-83b56a8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PageViewInfo-master-b138bbf.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PagedTiffHandler-master-ee928a9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PagesList-master-b41ee3b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PaginateText-master-ca40c1e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PanScroll-master-271cf2d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ParentPage-master-9b47665.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ParserFunctions-master-2764c09.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ParserMigration-master-9c040f4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PasswordlessLogin-master-72626eb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Patroller-master-d35bdec.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PdfHandler-master-69da294.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PerPageLanguage-master-1ec2b2f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PerPageLicense-master-4901492.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PerformanceInspector-master-efb8290.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Petition-master-f4d67f4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PhabTaskGraph-master-cde17d4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Phonos-master-2d21bc3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PhotoSwipe-master-1bae94f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PhpHighlight-master-a57c971.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PhpTags-master-9897d54.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PhpTagsFunctions-master-9ca8656.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PhpTagsMaps-master-0aa8081.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PhpTagsSMW-master-6ac2589.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PhpTagsSPARQL-master-def9d3d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PhpTagsStorage-master-0680704.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PhpTagsWidgets-master-2f24fa1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PhpTagsWiki-master-d3e77d4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PictureGame-master-68b9d89.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PipeEscape-master-4582700.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PluggableAuth-master-2001e8a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PluggableSSO-master-2263c5b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Poem-master-c433c06.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Poll-master-f1bc212.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PollNY-master-5f0d18a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Polyglot-master-c9bc765.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PoolCounter-master-0e15f94.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PopcornEditor-master-15afa94.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PopupAlerts-master-0a80224.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Popups-master-9cb4f45.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PreferencesList-master-dde2560.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Prezi-master-f8029e6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PrimarySources-master-95358f4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PrincePDF-master-2a1348b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PrivateDomains-master-566ce0b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PronunciationRecording-master-b9e6d95.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ProofreadPage-master-ee092a6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Prop-master-45f1cd0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PropertySuggester-master-fd27d10.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ProtectSite-master-283befa.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ProtectionIndicator-master-24a8818.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PurgeClickThrough-master-bf23c77.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Push-master-4737ec3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PushToWatch-master-72695ad.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/PwnedPasswords-master-db0f37c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Quantcast-master-95584d5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/QuickGV-master-ee05e76.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/QuickInstantCommons-master-e109518.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/QuickResponse-master-87f29ec.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/QuickSearchLookup-master-228e929.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/QuickSurveys-master-170d80b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Quiz-master-d48f149.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/QuizGame-master-ec33aec.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RSS-master-1ab96ff.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RT-master-b96cdef.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RandomArea-master-481c86e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RandomGameUnit-master-85af9ba.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RandomImage-master-bb29709.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RandomImageByCategory-master-0c9ccc5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RandomInCategory-master-f6f2301.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RandomPages-master-1d0c95a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RandomSelection-master-7da39c3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ReadingLists-master-74d5888.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RealMe-master-5b56f6e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Realnames-master-e6b480c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ReassignEdits-master-9995e37.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Recoin-master-2bb8597.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RedirectManager-master-2aedf99.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RefreshSpecial-master-6b1f935.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RegexBlock-master-5666619.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RegexFun-master-a57c2af.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RegexFunctions-master-f8992fa.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RegularTooltips-master-82438f7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RelMicroformat-master-28e3f51.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RelatedArticles-master-1560348.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RelatedSites-master-653da10.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Renameuser-master-972b990.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ReplaceSet-master-9793d79.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ReplaceText-master-8d77ba0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Report-master-4c7e3c4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RevisionCommentSupplement-master-40e9974.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RevisionSlider-master-d1be664.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/RightFunctions-master-69c64fd.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/S5SlideShow-master-7be529f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SSLClientAuthentication-master-3dced0f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SVGEdit-master-9e5bd7e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SacredText-master-6840f81.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SafeDelete-master-a802578.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SandboxLink-master-4d9d7fa.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Sarcasm-master-cb0d8fe.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SaveSpinner-master-5ca9a4f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Score-master-6e793ba.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Screenplay-master-ed484ab.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Scribe-master-56c7b2a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Scribunto-master-b0cbcff.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ScrollableTables-master-baedc6a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SearchExtraNS-master-dd0028d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SearchStats-master-b21fe10.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SearchThumbs-master-8324d63.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SearchVue-master-7816af0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SectionDisqus-master-8e5ac9b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SecureAuth-master-a9cd170.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SecureHTML-master-988e32a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SecureLinkFixer-master-0b37a34.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SecurePoll-master-e832139.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SecureSessions-master-a4ea80c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SecurityApi-master-24e336d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SelectCategory-master-50a4bcf.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SelectTag-master-16eaaf2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SemanticACL-master-3fa0840.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SemanticBundle-master-d9f06c6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SemanticDependency-master-5e0b167.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SemanticDrilldown-master-eaab54f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SemanticGenealogy-master-7caa02e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SemanticImageAnnotator-master-dc00280.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SemanticImageInput-master-888660d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SemanticInternalObjects-master-d3e10b2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SemanticPageSeries-master-8c0b5fc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SemanticRESTAPI-master-15a12bc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SemanticRating-master-47d79a8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SemanticSifter-master-5b90496.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SemanticWebBrowser-master-4b1cc77.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SendGrid-master-bb4831c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Sentry-master-1c315e7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Share-master-f3f5fff.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SharedHelpPages-master-8f143d3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Shibboleth-master-97fcba5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ShortUrl-master-8fbea6f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ShoutWikiAPI-master-16e45ad.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ShoutWikiAds-master-45f45b9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ShowMe-master-0200ee2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ShowRealUsernames-master-4817e9a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SideBarMenu-master-2f02470.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SidebarDonateBox-master-b78ce42.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SignWritingMediaWikiPlugin-master-e82eac2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SimilarEditors-master-5ad964b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SimpleCalendar-master-1e34533.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SimpleChanges-master-d2e29df.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SimpleSAMLphp-master-b6257a0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SimpleSort-master-c4c9c39.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SiteMatrix-master-f42cc72.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SiteMetrics-master-32dc2f5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SiteSettings-master-6888314.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SkinPerNamespace-master-db61c7c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SkinPerPage-master-fb0cd9b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SlimboxThumbs-master-2175a48.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SmiteSpam-master-1a12d42.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SocialLogin-master-3c66aca.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SocialProfile-master-7fc561a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Sofa-master-c698bed.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SoftRedirector-master-35c49ed.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SoftwareVersion-master-ab92f45.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SoundManager2Button-master-97cbd53.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SpamBlacklist-master-3e6ff1e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SpamDiffTool-master-b61b41d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SpamRegex-master-89022d5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Spark-master-026931e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SparkPost-master-e5c217c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Special404-master-8607349.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SpecialNamespaces-master-dcfac84.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SpellingApi-master-048c6d5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SpellingDictionary-master-fcdeec4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SphinxSearch-master-d9fd704.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SplitPrivateWiki-master-0a3bddd.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SportsTeams-master-4f1ec98.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/StaffEdits-master-b5f72d3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/StaffPowers-master-31b560b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/StalkerLog-master-0f5bb9f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/StandardDialogs-master-c257664.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/StarterWiki-master-ce83eef.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/StatCounter-master-26eba4b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/StickToThatLanguage-master-19083ea.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/StickyTOC-master-a440475.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/StlHandler-master-adbfc04.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/StopForumSpam-master-53e0bed.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/StringFunctionsEscaped-master-7d060f7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/StructuredNavigation-master-e867392.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SubPageList3-master-eac79bc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SubpageFun-master-0a3cd38.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SubpageSortkey-master-e67230d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Sudo-master-a23f406.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Survey-master-62c0fcb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SwiftMailer-master-6e56ea7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/SyntaxHighlight_GeSHi-master-91f7fc1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TEI-master-42a7823.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Tabber-master-4aa0cb6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Tabs-master-86d9754.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TemplateData-master-28c1471.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TemplateSandbox-master-595122b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TemplateStyles-master-38aaa56.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TemplateWizard-master-2c47921.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TestLanguageNameGrammar-master-c1468ad.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TextExtracts-master-79756fd.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TextScroller-master-3e3c061.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Thanks-master-f128128.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TheWikipediaLibrary-master-e174b6d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Theme-master-a7c2771.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ThrottleOverride-master-7b048c7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TimeMachine-master-c3b4174.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TimedMediaHandler-master-346752a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TimelineTable-master-bb9f771.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TinyMCE-master-969cbbc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TitleBlacklist-master-21964ef.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TitleIcon-master-5716fda.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TitleKey-master-6be6178.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TocTree-master-2345480.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Toolhub-master-b711e59.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Tooltip-master-7e31c78.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TopTenPages-master-385c889.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TorBlock-master-9af4537.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Translate-master-4b61c9d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TranslateSvg-master-01e3eb4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TranslationNotifications-master-bdb79c5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TrustedXFF-master-a2c6e18.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TuleapIntegration-master-d89becb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TuleapWikiFarm-master-eb878a9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TweetANew-master-26403f6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TwitterCards-master-9aa6d8d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TwitterLogin-master-6ada565.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TwitterTag-master-8273387.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TwnMainPage-master-a1fe17b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/TwoColConflict-master-cf8526a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UIFeedback-master-5235761.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UILangCode-master-fd0a67f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UnCaptcha-master-513fed6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UnicodeConverter-master-f715f9b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UnifiedTaskOverview-master-39ea590.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UniversalLanguageSelector-master-a26b071.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UnlinkedWikibase-master-6bab65c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UnusedRedirects-master-f74e0a1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UpdateMediaWiki-master-fb158c5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UploadBlacklist-master-013fb21.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UploadWizard-master-4193cb1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UploadsLink-master-33064d8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UrlGetParameters-master-f53f580.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UrlShortener-master-3063450.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UseResource-master-7f84c38.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UserAgreement-master-e9628fa.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UserExport-master-1b40e37.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UserFunctions-master-afbb36e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UserGroups-master-1774b73.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UserMerge-master-581898b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UserOptionStats-master-008eaf7.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UserPageEditProtection-master-1cbdc7a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UserPageViewTracker-master-97db30b.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UserProtect-master-0700a06.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UserStatus-master-e691989.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/UserThrottle-master-56f7918.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/VEForAll-master-bf8aecc.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/VIKI-master-4702b6c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Variables-master-9881c17.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/VersionCompare-master-e7cbedd.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Video-master-06b11ed.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Views-master-e700c87.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/VikiSemanticTitle-master-1def213.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/VikiTitleIcon-master-3550641.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/VipsScaler-master-9cdab3c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/VisualEditor-master-45f3774.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/VoteNY-master-d8d52a5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/VueTest-master-dda7c72.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WSOAuth-master-4e38c6c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WantedPagesFromNS-master-4070aa0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WatchAnalytics-master-4b2a130.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WatchSubpages-master-3d3e164.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WebAuthn-master-341f3ae.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WebChat-master-896cdb5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WebDAV-master-ca28b37.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WebDAVClientIntegration-master-6061851.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WebDAVMinorSave-master-162e482.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WebToolsManager-master-d397bb0.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WhiteSpace-master-10eb033.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WhitelistPages-master-23dc3f1.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WhoIsWatching-master-e768b25.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Whoops-master-dc34bb2.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WhosOnline-master-c910d0e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Widgets-master-89240d5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Wigo3-master-d443b5d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikEdDiff-master-9c77ec4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikiArticleFeeds-master-0fd7c50.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikiCategoryTagCloud-master-4ef5253.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikiEditor-master-e57eac9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikiForum-master-5e65e5f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikiLambda-master-fbfb803.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikiLexicalData-master-633e7fb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikiLove-master-efe035a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikiLovesMonuments-master-299735f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikiSEO-master-f6fe791.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikiShare-master-e1fc3a3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikiTextLoggedInOut-master-8bf9d8e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikiToLDAP-master-f712109.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikiVideos-master-765a8ef.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Wikibase-master-a856c41.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikibaseCirrusSearch-master-8f4f761.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikibaseLexeme-master-bfb058e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikibaseLexemeCirrusSearch-master-e36442a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikibaseManifest-master-cd85a36.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikibaseMediaInfo-master-4a094cd.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikibaseQualityConstraints-master-83d0b8d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikibaseStatementUpdater-master-57c4887.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Wikidata.org-master-a4d65bb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikidataPageBanner-master-1a02b28.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikimediaApiPortalOAuth-master-231d54e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikimediaBadges-master-86685d3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikimediaEditorTasks-master-a2bd4fb.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikimediaEvents-master-1507fb6.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikimediaIncubator-master-f31b225.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikimediaMaintenance-master-0394183.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikimediaMessages-master-ff39b05.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Wikisource-master-2d302d4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Wikispeech-master-160c50e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WikispeechSpeechDataCollector-master-deb4782.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Wikistories-master-59caf0c.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/WindowsAzureStorage-master-e906c49.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/Workflows-master-bd50256.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/XAnalytics-master-772470a.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/XSL-master-7113e10.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/XenForoAuth-master-86fbca3.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/YetAnotherKeywords-master-ab1d8d5.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/YotpoReviews-master-c5cfd4d.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/YouTube-master-5e96d28.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/ZoomableImages-master-0eb871f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/cldr-master-12b9aa8.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/examples-master-f742cd9.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/googleAnalytics-master-1fb645e.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/intersection-master-d2c844f.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/timeline-master-289fae4.tar.gz
curl -O https://extdist.wmflabs.org/dist/extensions/wikihiero-master-2fca9e6.tar.gz
