mv HeaderCount-master/HeaderCount-master HeaderCount
mv HeaderFooter-master/HeaderFooter-master HeaderFooter
mv iann-widget-for-mediawiki-master/iann-widget-for-mediawiki-master iann-widget-for-mediawiki
mv javascriptslideshow-master/javascriptslideshow-master JavascriptSlideshow
mv LinkAttributes-master/LinkAttributes-master LinkAttributes
mv lscache_mediawiki-master/lscache_mediawiki-master LsCache
mv ManageWiki-master/ManageWiki-master ManageWiki
mv mediawiki-antispam-master/mediawiki-antispam-master Antispam
mv mediawiki-aws-s3-master/mediawiki-aws-s3-master AwsS3
mv MediaWiki-ConsoleOutput-master/MediaWiki-ConsoleOutput-master ConsoleOutput
mv mediawiki-coorconv-master/mediawiki-coorconv-master Coorconv
mv MediaWiki-CopyWatchers-master/MediaWiki-CopyWatchers-master CopyWatchers
mv MediaWiki-Counter-master/MediaWiki-Counter-master Counter
mv MediaWiki-DynamicRedirect-master/MediaWiki-DynamicRedirect-master DynamicRedirect
mv mediawiki-email-login-master/mediawiki-email-login-master EmailLogin
mv mediawiki-emailuser-html-master/mediawiki-emailuser-html-master EmailuserHtml
mv mediawiki-embed-spotify-master/mediawiki-embed-spotify-master EmbedSpotify
mv MediaWiki-Extension-AgeClassification-master/MediaWiki-Extension-AgeClassification-master AgeClassification
mv mediawiki-extension-crowdsec-master/mediawiki-extension-crowdsec-master CrowdSec
mv mediawiki-extension-datatables-master/mediawiki-extension-datatables-master DataTables
mv MediaWiki-Extension-DonateButton-master/MediaWiki-Extension-DonateButton-master DonateButton
mv mediawiki-extension-DownloadBook-master/mediawiki-extension-DownloadBook-master DownloadBook
mv Mediawiki-Extension-HeaderExtension-master/Mediawiki-Extension-HeaderExtension-master Header
mv mediawiki-extension-JQuerySnowfall-master/mediawiki-extension-JQuerySnowfall-master JQuerySnowfall
mv mediawiki-extension-JsCalendar-master/mediawiki-extension-JsCalendar-master JsCalendar
mv mediawiki-extension-Metrica-master/mediawiki-extension-Metrica-master Metrica
mv mediawiki-extension-Mustache_i18n-master/mediawiki-extension-Mustache_i18n-master MustacheI18n
mv mediawiki-extension-Plausible-master/mediawiki-extension-Plausible-master Plausible
mv mediawiki-extension-QuickUploadZone-master/mediawiki-extension-QuickUploadZone-master QuickUploadZone
mv MediaWiki-Extension-RefreshSiteStatsTable-master/MediaWiki-Extension-RefreshSiteStatsTable-master RefreshSiteStatsTable
mv mediawiki-extensions-AcceleratedMobilePages-master/mediawiki-extensions-AcceleratedMobilePages-master AcceleratedMobilePages
mv mediawiki-extensions-Ainut-master/mediawiki-extensions-Ainut-master Ainut
mv mediawiki-extensions-BlueSpiceUpgradeHelper-master/mediawiki-extensions-BlueSpiceUpgradeHelper-master BlueSpiceUpgradeHelper
mv mediawiki-extensions-CBxHandler-master/mediawiki-extensions-CBxHandler-master CBxHandler
mv mediawiki-extensions-cloudflare-master/mediawiki-extensions-cloudflare-master Cloudflare
mv mediawiki-extensions-DataProvider-master/mediawiki-extensions-DataProvider-master DataProvider
mv mediawiki-extensions-ditaa-master/mediawiki-extensions-ditaa-master Ditaa
mv mediawiki-extensions-DonateBoxInSidebar-master/mediawiki-extensions-DonateBoxInSidebar-master DonateBoxInSidebar
mv mediawiki-extensions-DummyFandoomMainpageTags-master/mediawiki-extensions-DummyFandoomMainpageTags-master DummyFandoomMainpageTags
mv mediawiki-extensions-EditCountNeue-master/mediawiki-extensions-EditCountNeue-master EditCountNeue
mv mediawiki-extensions-EmbedVideo-master/mediawiki-extensions-EmbedVideo-master EmbedVideo
mv mediawiki-extensions-FileSystemImageServer-master/mediawiki-extensions-FileSystemImageServer-master FileSystemImageServer
mv mediawiki-extensions-GetUserName-master/mediawiki-extensions-GetUserName-master GetUserName
mv mediawiki-extensions-Info-master/mediawiki-extensions-Info-master Info
mv MediaWiki-Extension-SkinCustomiser-master/MediaWiki-Extension-SkinCustomiser-master SkinCustomiser
mv mediawiki-extensions-LightGallery-master/mediawiki-extensions-LightGallery-master LightGallery
mv mediawiki-extensions-ListDuplicateUsers-master/mediawiki-extensions-ListDuplicateUsers-master ListDuplicateUsers
mv mediawiki-extensions-magicallinkers-master/mediawiki-extensions-magicallinkers-master MagicalLinkers
mv mediawiki-extensions-MetaDescriptionTag-master/mediawiki-extensions-MetaDescriptionTag-master MetaDescriptionTag
mv mediawiki-extensions-MultiPurge-master/mediawiki-extensions-MultiPurge-master MultiPurge
mv mediawiki-extensions-NewDuplicateUserMessage-master/mediawiki-extensions-NewDuplicateUserMessage-master NewDuplicateUserMessage
mv mediawiki-Extension-SpecialUserScore-master/mediawiki-Extension-SpecialUserScore-master SpecialUserScore
mv mediawiki-extensions-PlaceNewSection-master/mediawiki-extensions-PlaceNewSection-master PlaceNewSection
mv mediawiki-extensions-SaferHTMLTag-master/mediawiki-extensions-SaferHTMLTag-master SaferHTMLTag
mv mediawiki-extensions-SaneCase-master/mediawiki-extensions-SaneCase-master SaneCase
mv mediawiki-extensions-Settings-master/mediawiki-extensions-Settings-master Settings
mv mediawiki-extensions-ShortDescription-master/mediawiki-extensions-ShortDescription-master ShortDescription
mv mediawiki-extensions-StubUserWikiAuth-master/mediawiki-extensions-StubUserWikiAuth-master StubUserWikiAuth
mv MediaWiki-ExtensionStatus-master/MediaWiki-ExtensionStatus-master ExtensionStatus
mv mediawiki-extensions-TemplateStylesExtender-master/mediawiki-extensions-TemplateStylesExtender-master TemplateStylesExtender
mv MediaWikiExtensionSummaryRequired-master/MediaWikiExtensionSummaryRequired-master SummaryRequired
mv mediawiki-extensions-UserLoginLog-master/mediawiki-extensions-UserLoginLog-master UserLoginLog
mv mediawiki-extensions-wikioutliner-master/mediawiki-extensions-wikioutliner-master WikiOutliner
mv mediawiki-extensions-YouTrackTicket-master/mediawiki-extensions-YouTrackTicket-master YouTrackTicket
mv MediaWiki-Extension--UserAdmin-master/MediaWiki-Extension--UserAdmin-master UserAdmin
mv mediawiki-extension-uservoice-master/mediawiki-extension-uservoice-master UserVoice
mv mediawiki-extension-VigLink-master/mediawiki-extension-VigLink-master VigLink
mv MediaWiki-Extension-WimaAdvertising-master/MediaWiki-Extension-WimaAdvertising-master WimaAdvertising
mv Mediawiki-Firebase-master/Mediawiki-Firebase-master Firebase
mv Mediawiki-FlowdockNotify-master/Mediawiki-FlowdockNotify-master FlowdockNotify
mv mediawiki-GetPageInfo-master/mediawiki-GetPageInfo-master GetPageInfo
mv mediawiki-github-commit-master/mediawiki-github-commit-master GithubCommit
mv mediawiki-gittip-widget-master/mediawiki-gittip-widget-master GittipWidget
mv MediaWiki-GoogleCodePrettify-master/MediaWiki-GoogleCodePrettify-master GoogleCodePrettify
mv mediawiki-GoogleRichCards-master/mediawiki-GoogleRichCards-master GoogleRichCards
mv mediawiki-GTag-master/mediawiki-GTag-master GTag
mv mediawiki-iframe-master/mediawiki-iframe-master Iframe
mv mediawiki-internalwhitelist-master/mediawiki-internalwhitelist-master InternalWhitelist
mv mediawiki-language-code-master/mediawiki-language-code-master LanguageCode
mv mediawiki-lazyload-master/mediawiki-lazyload-master Lazyload
mv mediawiki-LdapAuth-master/mediawiki-LdapAuth-master LdapAuth
mv mediawiki-linebreaks-extension-master/mediawiki-linebreaks-extension-master Linebreaks
mv mediawiki-link-to-archive-master/mediawiki-link-to-archive-master LinkToArchive
mv mediawiki-ListTransclusions-master/mediawiki-ListTransclusions-master ListTransclusions
mv mediawiki-mail-recentchanges-master/mediawiki-mail-recentchanges-master MailRecentchanges
mv mediawiki-mathjax-master/mediawiki-mathjax-master mathjax
mv mediawiki-MediaWikiAuth-master/mediawiki-MediaWikiAuth-master MediaWikiAuth
mv mediawiki-memento-headers-master/mediawiki-memento-headers-master MementoHeaders
mv Mediawiki-Model-master/Mediawiki-Model-master Model
mv mediawiki-moderation-master/mediawiki-moderation-master Moderation
mv mediawiki-movetoskin-master/mediawiki-movetoskin-master MoveToSkin
mv mediawiki-nagvis-master/mediawiki-nagvis-master Nagvis
mv mediawiki-nbbc-bbcode-master/mediawiki-nbbc-bbcode-master NbbcBbcode
mv mediawiki-numberedheadings-master/mediawiki-numberedheadings-master NumberedHeadings
mv Mediawiki-OpauthLogin-master/Mediawiki-OpauthLogin-master OpauthLogin
mv Mediawiki-Opauth-master/Mediawiki-Opauth-master Opauth
mv mediawiki-page-attachment-master/mediawiki-page-attachment-master PageAttachment
mv MediaWiki-pChart4mw-master/MediaWiki-pChart4mw-master PChart4mw
mv mediawiki-RecentChangesLogFilter-master/mediawiki-RecentChangesLogFilter-master RecentChangesLogFilter
mv MediaWiki-RecentChangesOption-master/MediaWiki-RecentChangesOption-master RecentChangesOption
mv mediawikiRemoveRedlinks-master/mediawikiRemoveRedlinks-master RemoveRedlinks
mv mediawiki-sections-count-master/mediawiki-sections-count-master SectionsCount
mv mediawiki-shibboleth-authentication-master/mediawiki-shibboleth-authentication-master ShibbolethAuthentication
mv mediawiki-ShoogleTweet-master/mediawiki-ShoogleTweet-master ShoogleTweet
mv mediawiki_simple_breadcrumb-master/mediawiki_simple_breadcrumb-master SimpleBreadcrumb
mv mediawiki-special-realname-master/mediawiki-special-realname-master SpecialRealname
mv mediawiki-SubpageWatchlist-master/mediawiki-SubpageWatchlist-master SubpageWatchlist
mv mediawiki-third-party-session-verification-master/mediawiki-third-party-session-verification-master ThirdPartySessionVerification
mv MediaWiki-TimeConvert-master/MediaWiki-TimeConvert-master TimeConvert
mv mediawiki-uploadconvert-master/mediawiki-uploadconvert-master UploadConvert
mv mediawiki-ViewProtect-master/mediawiki-ViewProtect-master ViewProtect
mv Mediawiki-Views-master/Mediawiki-Views-master Views
mv PageCrossReference-master/PageCrossReference-master PageCrossReference
mv PageEditRestrictions-master/PageEditRestrictions-master PageEditRestrictions
mv PageImporter-master/PageImporter-master PageImporter
mv ParserHooks-master/ParserHooks-master ParserHooks
mv PdfBook-master/PdfBook-master PdfBook
mv PDFEmbed-master/PDFEmbed-master PDFEmbed
mv PerformanceMonitor-master/PerformanceMonitor-master PerformanceMonitor
mv php-mediawiki-jiki-master/php-mediawiki-jiki-master Jiki
mv php-namumark-mediawiki-master/php-namumark-mediawiki-master Namumark
mv Pickle-master/Pickle-master Pickle
mv Piwo-master/Piwo-master Piwo
mv PlantUML-master/PlantUML-master PlantUML
mv PlasticMW-master/PlasticMW-master PlasticMW
mv PluggableSSO-master/PluggableSSO-master PluggableSSO
mv Pluso-master/Pluso-master Pluso
mv PortableInfobox-master/PortableInfobox-master PortableInfobox
mv Preloader-master/Preloader-master Preloader
mv PropChainsHelper-master/PropChainsHelper-master PropChainsHelper
mv PubSubHubbubSubscriber-master/PubSubHubbubSubscriber-master PubSubHubbubSubscriber
mv Purge-master/Purge-master Purge
mv PurgePage-master/PurgePage-master PurgePage
mv PushAll-master/PushAll-master PushAll
mv QRLite-master/QRLite-master QRLite
mv QualityAssuranceMWExtension-master/QualityAssuranceMWExtension-master QualityAssurance
mv QueryViz-master/QueryViz-master QueryViz
mv ratepage-master/ratepage-master Ratepage
mv RDFIO-master/RDFIO-master RDFIO
mv RecentActivity-master/RecentActivity-master RecentActivity
mv RecordWizard-master/RecordWizard-master RecordWizard
mv RecurrentEventCalendar-master/RecurrentEventCalendar-master RecurrentEventCalendar
mv RelationLinks-master/RelationLinks-master RelationLinks
mv RelativePageLinks-master/RelativePageLinks-master RelativePageLinks
mv RemovePII-master/RemovePII-master RemovePII
mv RenderTheFuck-master/RenderTheFuck-master RenderTheFuck
mv RenderThumbnails-master/RenderThumbnails-master RenderThumbnails
mv reviews-master/reviews-master Reviews
mv ROT13-master/ROT13-master ROT13
mv RottenLinks-master/RottenLinks-master RottenLinks
mv S5SlideShow-master/S5SlideShow-master S5SlideShow
mv Scopus-master/Scopus-master Scopus
mv ScryfallLinks-master/ScryfallLinks-master ScryfallLinks
mv SearchBlox-master/SearchBlox-master SearchBlox
mv SecureInclude-master/SecureInclude-master SecureInclude
mv SemanticActions-master/SemanticActions-master SemanticActions
mv SemanticApprovedRevs-master/SemanticApprovedRevs-master SemanticApprovedRevs
mv SemanticBreadcrumbLinks-master/SemanticBreadcrumbLinks-master SemanticBreadcrumbLinks
mv SemanticBundle-master/SemanticBundle-master SemanticBundle
mv SemanticCite-master/SemanticCite-master SemanticCite
mv SemanticCompoundQueries-master/SemanticCompoundQueries-master SemanticCompoundQueries
mv SemanticDataImport-master/SemanticDataImport-master SemanticDataImport
mv SemanticDependencyUpdater-master/SemanticDependencyUpdater-master SemanticDependencyUpdater
mv SemanticDummyEditor-master/SemanticDummyEditor-master SemanticDummyEditor
mv SemanticExternalQueryLookup-master/SemanticExternalQueryLookup-master SemanticExternalQueryLookup
mv SemanticExtraSpecialProperties-master/SemanticExtraSpecialProperties-master SemanticExtraSpecialProperties
mv SemanticFormsSelect-master/SemanticFormsSelect-master SemanticFormsSelect
mv SemanticGlossary-master/SemanticGlossary-master SemanticGlossary
mv SemanticImageAnnotator-master/SemanticImageAnnotator-master SemanticImageAnnotator
mv SemanticImageCaption-master/SemanticImageCaption-master SemanticImageCaption
mv SemanticInterlanguageLinks-master/SemanticInterlanguageLinks-master SemanticInterlanguageLinks
mv SemanticMailMerge-master/SemanticMailMerge-master SemanticMailMerge
mv SemanticMediaWiki-master/SemanticMediaWiki-master SemanticMediaWiki
mv SemanticMetaTags-master/SemanticMetaTags-master SemanticMetaTags
mv SemanticMustacheFormat-master/SemanticMustacheFormat-master SemanticMustacheFormat
mv Semantic-Need-master/Semantic-Need-master Semantic-Need
mv SemanticNotifications-master/SemanticNotifications-master SemanticNotifications
mv SemanticOLAP-master/SemanticOLAP-master SemanticOLAP
mv SemanticQueryInterface-master/SemanticQueryInterface-master SemanticQueryInterface
mv SemanticResultFormats-master/SemanticResultFormats-master SemanticResultFormats
mv SemanticScribunto-master/SemanticScribunto-master SemanticScribunto
mv SemanticSignup-master/SemanticSignup-master SemanticSignup
mv SemanticStructuredDiscussions-master/SemanticStructuredDiscussions-master SemanticStructuredDiscussions
mv SemanticTasks-master/SemanticTasks-master SemanticTasks
mv SemanticWatchlist-master/SemanticWatchlist-master SemanticWatchlist
mv SemanticWikibase-master/SemanticWikibase-master SemanticWikibase
mv Serialization-master/Serialization-master Serialization
mv Shariff-Mediawiki-master/Shariff-Mediawiki-master Shariff-Mediawiki
mv Shiny-master/Shiny-master Shiny
mv SimpleBatchUpload-master/SimpleBatchUpload-master SimpleBatchUpload
mv SimpleBlogPage-master/SimpleBlogPage-master SimpleBlogPage
mv simplefeed-master/simplefeed-master SimpleFeed
mv SimpleMathJax-master/SimpleMathJax-master SimpleMathJax
mv SimpleMath-master/SimpleMath-master SimpleMath
mv SimpleSkins-master/SimpleSkins-master SimpleSkins
mv SimpleTable-master/SimpleTable-master SimpleTable
mv SimpleTooltip-master/SimpleTooltip-master SimpleTooltip
mv SiteMeterMW-master/SiteMeterMW-master SiteMeterMW
mv skinny-master/skinny-master Skinny
mv SlackNotifications-master/SlackNotifications-master SlackNotifications
mv SmartIndex-master/SmartIndex-master SmartIndex
mv Socialcast-PHP-Samples-master/Socialcast-PHP-Samples-master Socialcast-PHP-Samples
mv SocialMediaImage--Mediawiki-Extension--master/SocialMediaImage--Mediawiki-Extension--master SocialMediaImage--Mediawiki-Extension-
mv SortChars-master/SortChars-master SortChars
mv SourceProtection-master/SourceProtection-master SourceProtection
mv SparqlCharts-master/SparqlCharts-master SparqlCharts
mv SparqlResultFormat-master/SparqlResultFormat-master SparqlResultFormat
mv Spoilers-master/Spoilers-master Spoilers
mv SpriteSheet-master/SpriteSheet-master SpriteSheet
mv SSLClientAuth-master/SSLClientAuth-master SSLClientAuth
mv StorePdfArticleInAlfresco-master/StorePdfArticleInAlfresco-master StorePdfArticleInAlfresco
mv storify-widget-for-mediawiki-master/storify-widget-for-mediawiki-master storify-widget-for-mediawiki
mv Streamer-master/Streamer-master Streamer
mv Substitutor-master/Substitutor-master Substitutor
mv SummaryCards-master/SummaryCards-master SummaryCards
mv svetovid-master/svetovid-master svetovid
mv SwaggerDoc-master/SwaggerDoc-master SwaggerDoc
mv Sync-master/Sync-master Sync
mv SyntaxHighlighter-master/SyntaxHighlighter-master SyntaxHighlighter
mv SyntaxHighlightPages-master/SyntaxHighlightPages-master SyntaxHighlightPages
mv TalkRight-master/TalkRight-master TalkRight
mv TemplateEdit-master/TemplateEdit-master TemplateEdit
mv TemplateRest-master/TemplateRest-master TemplateRest
mv TemplateTableReloaded-master/TemplateTableReloaded-master TemplateTableReloaded
mv Testimonials-master/Testimonials-master Testimonials
mv ThumbParser-master/ThumbParser-master ThumbParser
mv TimedNotify-master/TimedNotify-master TimedNotify
mv TimelineStats-master/TimelineStats-master TimelineStats
mv TimezoneConverter-master/TimezoneConverter-master TimezoneConverter
mv TranslateWiki-master/TranslateWiki-master TranslateWiki
mv TreeAndMenu-master/TreeAndMenu-master TreeAndMenu
mv tweetiki-master/tweetiki-master tweetiki
mv ulogin-MediaWiki-master/ulogin-MediaWiki-master ulogin-MediaWiki
mv UndeleteBatch-master/UndeleteBatch-master UndeleteBatch
mv UniversalSuggester-master/UniversalSuggester-master UniversalSuggester
mv Upload2Commons-master/Upload2Commons-master Upload2Commons
mv UploadFields-master/UploadFields-master UploadFields
mv UserHistory-master/UserHistory-master UserHistory
mv UsersWatchlist-master/UsersWatchlist-master UsersWatchlist
mv Validator-master/Validator-master Validator
mv VariablesLua-master/VariablesLua-master VariablesLua
mv VectorUp-master/VectorUp-master VectorUp
mv ViewTable-master/ViewTable-master ViewTable
mv ViewWikitext-master/ViewWikitext-master ViewWikitext
mv VoiceCommander-master/VoiceCommander-master VoiceCommander
mv WatchGroup-master/WatchGroup-master WatchGroup
mv WhatsNearby-master/WhatsNearby-master WhatsNearby
mv Wiki2Ban-master/Wiki2Ban-master Wiki2Ban
mv WikiBanHammer-master/WikiBanHammer-master WikiBanHammer
mv WikiBanner-master/WikiBanner-master WikiBanner
mv WikibaseDataModel-master/WikibaseDataModel-master WikibaseDataModel
mv WikibaseEdtf-master/WikibaseEdtf-master WikibaseEdtf
mv WikibaseExport-master/WikibaseExport-master WikibaseExport
mv WikidataShow-master/WikidataShow-master WikidataShow
mv WikiDiscover-master/WikiDiscover-master WikiDiscover
mv wiki_figma-master/wiki_figma-master wiki_figma
mv Wikilog-master/Wikilog-master Wikilog
mv Wikimedia-SimpleRadiusAuth-master/Wikimedia-SimpleRadiusAuth-master Wikimedia-SimpleRadiusAuth
mv WikiRatingExtension-master/WikiRatingExtension-master WikiRatingExtension
mv WikiSearchFront-master/WikiSearchFront-master WikiSearchFront
mv WikiSearch-master/WikiSearch-master WikiSearch
mv wikistatistics-mediawiki-extension-master/wikistatistics-mediawiki-extension-master WikiStatistics
mv wiki-uturn-master/wiki-uturn-master WikiUturn
mv Wiretap-master/Wiretap-master Wiretap
mv wolfram_cdf-master/wolfram_cdf-master WolframCdf
mv wsarrays-master/wsarrays-master WsArrays
mv WSStats-master/WSStats-master WSStats
