tar -zxvf 3D-master-0de38a2.tar.gz
tar -zxvf AControlImageLink-master-61ce1d3.tar.gz
tar -zxvf AJAXPoll-master-5b1a66a.tar.gz
tar -zxvf AbsenteeLandlord-master-4eba21d.tar.gz
tar -zxvf AbuseFilter-master-7a6e063.tar.gz
tar -zxvf AbuseFilterBypass-master-4837809.tar.gz
tar -zxvf AccessControl-master-26337d7.tar.gz
tar -zxvf AccountInfo-master-a014977.tar.gz
tar -zxvf Acrolinx-master-bef47b6.tar.gz
tar -zxvf ActiveAbstract-master-85749a8.tar.gz
tar -zxvf AdManager-master-e50227c.tar.gz
tar -zxvf AddHTMLMetaAndTitle-master-44283c9.tar.gz
tar -zxvf AddMessages-master-c002cf6.tar.gz
tar -zxvf AddPersonalUrls-master-21eac9d.tar.gz
tar -zxvf AddThis-master-27d826a.tar.gz
tar -zxvf AdminLinks-master-d928f24.tar.gz
tar -zxvf AdvancedMeta-master-f416f43.tar.gz
tar -zxvf AdvancedSearch-master-665ea78.tar.gz
tar -zxvf AjaxShowEditors-master-f1e9f51.tar.gz
tar -zxvf AkismetKlik-master-ccc3932.tar.gz
tar -zxvf AllTimeZones-master-e313897.tar.gz
tar -zxvf AnchorHandler-master-8498664.tar.gz
tar -zxvf AnonPrivacy-master-1105e7c.tar.gz
tar -zxvf AntiSpoof-master-90f1cc9.tar.gz
tar -zxvf ApiFeatureUsage-master-9064ee2.tar.gz
tar -zxvf ApprovedRevs-master-d0b3590.tar.gz
tar -zxvf Arrays-master-a29815c.tar.gz
tar -zxvf ArticleCreationWorkflow-master-1c5825f.tar.gz
tar -zxvf ArticleFeedbackv5-master-dca0d35.tar.gz
tar -zxvf ArticleIndex-master-2b1ce4c.tar.gz
tar -zxvf ArticleMetaDescription-master-c56e9a2.tar.gz
tar -zxvf ArticlePlaceholder-master-b900af6.tar.gz
tar -zxvf ArticleRatings-master-8d1c237.tar.gz
tar -zxvf ArticleToCategory2-master-3867b0f.tar.gz
tar -zxvf Athena-master-4668910.tar.gz
tar -zxvf Auth_remoteuser-master-840c302.tar.gz
tar -zxvf AuthorProtect-master-c708d9a.tar.gz
tar -zxvf AutoCategoriseUploads-master-8021f3a.tar.gz
tar -zxvf AutoCreateCategoryPages-master-8a48985.tar.gz
tar -zxvf AutoGallery-master-c5525bf.tar.gz
tar -zxvf AutoProxyBlock-master-06f568a.tar.gz
tar -zxvf Awesomeness-master-679ce06.tar.gz
tar -zxvf Babel-master-ec99765.tar.gz
tar -zxvf BaseHooks-master-e5173bf.tar.gz
tar -zxvf BatchUserRights-master-779da6c.tar.gz
tar -zxvf BetaFeatures-master-74ec050.tar.gz
tar -zxvf BibManager-master-6745b11.tar.gz
tar -zxvf BiblioPlus-master-30f2a5c.tar.gz
tar -zxvf Blackout-master-db9b2f7.tar.gz
tar -zxvf BlockAndNuke-master-6fd2d64.tar.gz
tar -zxvf BlockInactive-master-70f28f5.tar.gz
tar -zxvf BlogPage-master-22e2baf.tar.gz
tar -zxvf BlueSpiceAbout-master-ca710f7.tar.gz
tar -zxvf BlueSpiceArticleInfo-master-99a4df0.tar.gz
tar -zxvf BlueSpiceArticlePreviewCapture-master-7f3c2b8.tar.gz
tar -zxvf BlueSpiceAuthors-master-de28cea.tar.gz
tar -zxvf BlueSpiceAvatars-master-8a880f7.tar.gz
tar -zxvf BlueSpiceBookshelf-master-f7dced8.tar.gz
tar -zxvf BlueSpiceCategoryCheck-master-df50444.tar.gz
tar -zxvf BlueSpiceCategoryManager-master-49e9c1e.tar.gz
tar -zxvf BlueSpiceChecklist-master-447eb6c.tar.gz
tar -zxvf BlueSpiceConfigManager-master-7ab3ca8.tar.gz
tar -zxvf BlueSpiceContextMenu-master-38148a9.tar.gz
tar -zxvf BlueSpiceCountThings-master-d476b91.tar.gz
tar -zxvf BlueSpiceCustomMenu-master-815bc93.tar.gz
tar -zxvf BlueSpiceDashboards-master-fc8bbeb.tar.gz
tar -zxvf BlueSpiceDistributionConnector-master-0e0b5db.tar.gz
tar -zxvf BlueSpiceEchoConnector-master-3debabe.tar.gz
tar -zxvf BlueSpiceEmoticons-master-ae10027.tar.gz
tar -zxvf BlueSpiceExpiry-master-7a5895c.tar.gz
tar -zxvf BlueSpiceExportTables-master-ca777f1.tar.gz
tar -zxvf BlueSpiceExtendedFilelist-master-a6b6182.tar.gz
tar -zxvf BlueSpiceExtendedSearch-master-5e3d343.tar.gz
tar -zxvf BlueSpiceExtendedStatistics-master-b501366.tar.gz
tar -zxvf BlueSpiceFilterableTables-master-0acd3ec.tar.gz
tar -zxvf BlueSpiceFlaggedRevsConnector-master-d3d24f8.tar.gz
tar -zxvf BlueSpiceFoundation-master-45e3f81.tar.gz
tar -zxvf BlueSpiceGroupManager-master-1fea36c.tar.gz
tar -zxvf BlueSpiceHideTitle-master-1a82600.tar.gz
tar -zxvf BlueSpiceInsertCategory-master-ccff15e.tar.gz
tar -zxvf BlueSpiceInsertFile-master-6d34121.tar.gz
tar -zxvf BlueSpiceInsertLink-master-bf45965.tar.gz
tar -zxvf BlueSpiceInsertMagic-master-4477161.tar.gz
tar -zxvf BlueSpiceInsertTemplate-master-2fdb60b.tar.gz
tar -zxvf BlueSpiceInterWikiLinks-master-3d1cc21.tar.gz
tar -zxvf BlueSpiceMultiUpload-master-0ff9485.tar.gz
tar -zxvf BlueSpiceNSFileRepoConnector-master-748d9b9.tar.gz
tar -zxvf BlueSpiceNamespaceCSS-master-08c0561.tar.gz
tar -zxvf BlueSpiceNamespaceManager-master-20a188b.tar.gz
tar -zxvf BlueSpicePageAccess-master-2d81bd0.tar.gz
tar -zxvf BlueSpicePageAssignments-master-cbebba8.tar.gz
tar -zxvf BlueSpicePageFormsConnector-master-583372f.tar.gz
tar -zxvf BlueSpicePageTemplates-master-647e0ae.tar.gz
tar -zxvf BlueSpicePageVersion-master-39eb963.tar.gz
tar -zxvf BlueSpicePagesVisited-master-6bb075b.tar.gz
tar -zxvf BlueSpicePermissionManager-master-96d799f.tar.gz
tar -zxvf BlueSpicePlayer-master-e7830d5.tar.gz
tar -zxvf BlueSpicePrivacy-master-0b8992d.tar.gz
tar -zxvf BlueSpiceProDistributionConnector-master-8822439.tar.gz
tar -zxvf BlueSpiceQrCode-master-d0a29f4.tar.gz
tar -zxvf BlueSpiceRSSFeeder-master-d6690ae.tar.gz
tar -zxvf BlueSpiceRating-master-cde7574.tar.gz
tar -zxvf BlueSpiceReadConfirmation-master-1054b10.tar.gz
tar -zxvf BlueSpiceReaders-master-a3ef375.tar.gz
tar -zxvf BlueSpiceReminder-master-b0ccd81.tar.gz
tar -zxvf BlueSpiceSMWConnector-master-8645c7a.tar.gz
tar -zxvf BlueSpiceSaferEdit-master-7470310.tar.gz
tar -zxvf BlueSpiceSignHere-master-954a4f9.tar.gz
tar -zxvf BlueSpiceSmartList-master-3ca9438.tar.gz
tar -zxvf BlueSpiceSocial-master-eb0a32f.tar.gz
tar -zxvf BlueSpiceSocialArticleActions-master-df06ce1.tar.gz
tar -zxvf BlueSpiceSocialBlog-master-5c6eb0f.tar.gz
tar -zxvf BlueSpiceSocialComments-master-eab9c2b.tar.gz
tar -zxvf BlueSpiceSocialMicroBlog-master-868a4d9.tar.gz
tar -zxvf BlueSpiceSocialProfile-master-fb0b96f.tar.gz
tar -zxvf BlueSpiceSocialRating-master-63ebeb9.tar.gz
tar -zxvf BlueSpiceSocialResolve-master-082456e.tar.gz
tar -zxvf BlueSpiceSocialTags-master-9a7fc4d.tar.gz
tar -zxvf BlueSpiceSocialTimelineUpdate-master-2a5dbeb.tar.gz
tar -zxvf BlueSpiceSocialTopics-master-7fd16f7.tar.gz
tar -zxvf BlueSpiceSocialWatch-master-53dc343.tar.gz
tar -zxvf BlueSpiceSocialWikiPage-master-c89c6ee.tar.gz
tar -zxvf BlueSpiceSubPageTree-master-fb4e43b.tar.gz
tar -zxvf BlueSpiceTagCloud-master-15a22bc.tar.gz
tar -zxvf BlueSpiceUEModuleBookPDF-master-d9cac9a.tar.gz
tar -zxvf BlueSpiceUEModuleDOCX-master-5519ead.tar.gz
tar -zxvf BlueSpiceUEModuleHTML-master-0a93499.tar.gz
tar -zxvf BlueSpiceUEModulePDF-master-5bb3761.tar.gz
tar -zxvf BlueSpiceUEModulePDFRecursive-master-d30a57d.tar.gz
tar -zxvf BlueSpiceUEModulePDFSubpages-master-f270dff.tar.gz
tar -zxvf BlueSpiceUEModuleTable2Excel-master-b0db7c9.tar.gz
tar -zxvf BlueSpiceUniversalExport-master-85d6191.tar.gz
tar -zxvf BlueSpiceUsageTracker-master-31fa174.tar.gz
tar -zxvf BlueSpiceUserInfo-master-fafc729.tar.gz
tar -zxvf BlueSpiceUserManager-master-3b06a60.tar.gz
tar -zxvf BlueSpiceUserSidebar-master-eb6c7c2.tar.gz
tar -zxvf BlueSpiceVisualDiff-master-a92cac4.tar.gz
tar -zxvf BlueSpiceVisualEditorConnector-master-950cbbc.tar.gz
tar -zxvf BlueSpiceWatchList-master-5bfee33.tar.gz
tar -zxvf BlueSpiceWhoIsOnline-master-f97eea2.tar.gz
tar -zxvf BlueSpiceWikiExplorer-master-f7a7e2f.tar.gz
tar -zxvf BoilerPlate-master-e1a4049.tar.gz
tar -zxvf BounceHandler-master-d09f83e.tar.gz
tar -zxvf BreadCrumbs-master-a3a7950.tar.gz
tar -zxvf BreadCrumbs2-master-400dbad.tar.gz
tar -zxvf BrickipediaExtra-master-498c1d8.tar.gz
tar -zxvf Buggy-master-adff480.tar.gz
tar -zxvf CIForms-master-653ee1a.tar.gz
tar -zxvf CSS-master-a8cafdb.tar.gz
tar -zxvf Calendar-master-0b7234a.tar.gz
tar -zxvf CampaignEvents-master-c72065e.tar.gz
tar -zxvf Campaigns-master-a35f17e.tar.gz
tar -zxvf Capiunto-master-21befed.tar.gz
tar -zxvf Cargo-master-95f5d16.tar.gz
tar -zxvf Carp-master-848f61a.tar.gz
tar -zxvf CatTalk-master-82716f3.tar.gz
tar -zxvf CategoryExplorer-master-381b75e.tar.gz
tar -zxvf CategoryLockdown-master-fea6b04.tar.gz
tar -zxvf CategorySortHeaders-master-0db2e22.tar.gz
tar -zxvf CategoryTagSorter-master-bd5f0a0.tar.gz
tar -zxvf CategoryTests-master-c466ee2.tar.gz
tar -zxvf CategoryTree-master-02fbb97.tar.gz
tar -zxvf CategoryWatch-master-dbf53e0.tar.gz
tar -zxvf CentralAuth-master-4005287.tar.gz
tar -zxvf CentralLogging-master-608b968.tar.gz
tar -zxvf CentralNotice-master-088aaf5.tar.gz
tar -zxvf Challenge-master-d0b4551.tar.gz
tar -zxvf ChangeAuthor-master-b31ad8d.tar.gz
tar -zxvf ChangeUserPasswords-master-851440a.tar.gz
tar -zxvf CharInsert-master-254a358.tar.gz
tar -zxvf CharRangeSpan-master-e295f12.tar.gz
tar -zxvf CheckUser-master-6da53df.tar.gz
tar -zxvf Checkpoint-master-c7ebbd4.tar.gz
tar -zxvf ChessBrowser-master-08db5d8.tar.gz
tar -zxvf CirrusSearch-master-155d5a1.tar.gz
tar -zxvf Cite-master-d9b2934.tar.gz
tar -zxvf CiteDrawer-master-2b492e8.tar.gz
tar -zxvf CiteThisPage-master-3579299.tar.gz
tar -zxvf Citoid-master-6cfccf2.tar.gz
tar -zxvf CleanChanges-master-4245d3e.tar.gz
tar -zxvf CloneDiff-master-107cf49.tar.gz
tar -zxvf CloseWikis-master-a6decda.tar.gz
tar -zxvf CodeEditor-master-4388be6.tar.gz
tar -zxvf CodeMirror-master-10958bc.tar.gz
tar -zxvf CodeReview-master-4df23fc.tar.gz
tar -zxvf Cognate-master-0895b90.tar.gz
tar -zxvf CognitiveProcessDesigner-master-a9d9380.tar.gz
tar -zxvf CollaborationKit-master-6b09c6a.tar.gz
tar -zxvf CollapsibleSections-master-3478a10.tar.gz
tar -zxvf CollapsibleVector-master-acede0a.tar.gz
tar -zxvf Collection-master-25bf4aa.tar.gz
tar -zxvf CommentStreams-master-1d55fd5.tar.gz
tar -zxvf Commentbox-master-e78f760.tar.gz
tar -zxvf Comments-master-c24eb8c.tar.gz
tar -zxvf CommonMessages-master-3165956.tar.gz
tar -zxvf CommonsMetadata-master-e53d2d6.tar.gz
tar -zxvf ConfigManager-master-7f7b5c1.tar.gz
tar -zxvf ConfirmAccount-master-bd447a3.tar.gz
tar -zxvf ConfirmEdit-master-2b96847.tar.gz
tar -zxvf CongressLookup-master-94c22fb.tar.gz
tar -zxvf ContactPage-master-d884bf8.tar.gz
tar -zxvf ContentTransfer-master-fc13df8.tar.gz
tar -zxvf ContentTranslation-master-3fedca9.tar.gz
tar -zxvf ContributionCredits-master-ef11d1f.tar.gz
tar -zxvf ContributionScores-master-d4dae78.tar.gz
tar -zxvf ContributionsList-master-47b3523.tar.gz
tar -zxvf Contributors-master-9d3e401.tar.gz
tar -zxvf CookieWarning-master-62d577a.tar.gz
tar -zxvf CosmosProfile-master-6879348.tar.gz
tar -zxvf CountDownClock-master-ed06b66.tar.gz
tar -zxvf CrawlableAllPages-master-291fd3d.tar.gz
tar -zxvf CreateAPage-master-701a046.tar.gz
tar -zxvf CreatePage-master-b249049.tar.gz
tar -zxvf CreatePageUw-master-56307d8.tar.gz
tar -zxvf CreateRedirect-master-3edca49.tar.gz
tar -zxvf CreateUserPage-master-f797551.tar.gz
tar -zxvf CreatedPagesList-master-2591c84.tar.gz
tar -zxvf CreditsSource-master-627b2b3.tar.gz
tar -zxvf DPLforum-master-7f58825.tar.gz
tar -zxvf DarkMode-master-2c6c85b.tar.gz
tar -zxvf Dashiki-master-f80dd32.tar.gz
tar -zxvf DataTable2-master-e6091ec.tar.gz
tar -zxvf DataTransfer-master-81be09e.tar.gz
tar -zxvf DateDiff-master-1168d08.tar.gz
tar -zxvf DebateTree-master-a447f56.tar.gz
tar -zxvf DebugMode-master-2afe90f.tar.gz
tar -zxvf DebugTemplates-master-cadad0b.tar.gz
tar -zxvf DeleteBatch-master-de43801.tar.gz
tar -zxvf DeleteOwn-master-7e58c60.tar.gz
tar -zxvf DeletePagesForGood-master-5515eec.tar.gz
tar -zxvf DeleteUserPages-master-20d3bd7.tar.gz
tar -zxvf Description2-master-4ba5e24.tar.gz
tar -zxvf DeviceMapLogCapture-master-b038a2f.tar.gz
tar -zxvf Diagnosis-master-d3da7df.tar.gz
tar -zxvf DidYouKnow-master-5a73439.tar.gz
tar -zxvf DisableAccount-master-fb1cab2.tar.gz
tar -zxvf Disambiguator-master-822429b.tar.gz
tar -zxvf Discourse-master-41b5baf.tar.gz
tar -zxvf DiscussionThreading-master-c9de08e.tar.gz
tar -zxvf DiscussionTools-master-d3a44b1.tar.gz
tar -zxvf DismissableSiteNotice-master-839125e.tar.gz
tar -zxvf DisplayTitle-master-47ee9cc.tar.gz
tar -zxvf DisqusTag-master-2fb96c6.tar.gz
tar -zxvf DocBookExport-master-30c7343.tar.gz
tar -zxvf DonationInterface-master-f8b4856.tar.gz
tar -zxvf DoubleWiki-master-2dc4da3.tar.gz
tar -zxvf DownloadCounter-master-aab5059.tar.gz
tar -zxvf Drafts-master-d858fa5.tar.gz
tar -zxvf DrawioEditor-master-4b2ae7b.tar.gz
tar -zxvf DumpsOnDemand-master-83543aa.tar.gz
tar -zxvf Duplicator-master-53c629d.tar.gz
tar -zxvf DynamicPageList-master-8391e73.tar.gz
tar -zxvf DynamicPageListEngine-master-190ce1a.tar.gz
tar -zxvf DynamicSidebar-master-2bf5bc0.tar.gz
tar -zxvf EasyWiki-master-cea1b26.tar.gz
tar -zxvf Echo-master-6430eab.tar.gz
tar -zxvf EditAccount-master-6067870.tar.gz
tar -zxvf EditNotify-master-a06f9c0.tar.gz
tar -zxvf EditSimilar-master-ac20b66.tar.gz
tar -zxvf EditSubpages-master-b046c0d.tar.gz
tar -zxvf EditUser-master-92a4fd0.tar.gz
tar -zxvf Editcount-master-54a6f3a.tar.gz
tar -zxvf EditcountAdditions-master-b6f3280.tar.gz
tar -zxvf Elastica-master-0a677c0.tar.gz
tar -zxvf ElectronPdfService-master-90dffd3.tar.gz
tar -zxvf EmailAuth-master-08b0156.tar.gz
tar -zxvf EmailAuthorization-master-a9d746e.tar.gz
tar -zxvf EmailCapture-master-9453ee7.tar.gz
tar -zxvf EmailDeletedPages-master-96767e8.tar.gz
tar -zxvf EmailDiff-master-48d053e.tar.gz
tar -zxvf EmergencyCaptcha-master-690c204.tar.gz
tar -zxvf EncryptedUploads-master-6a983ed.tar.gz
tar -zxvf EnhanceContactForm-master-e0225bf.tar.gz
tar -zxvf EnhancedUpload-master-886a77c.tar.gz
tar -zxvf EntitySchema-master-70addd0.tar.gz
tar -zxvf ErrorHandler-master-4cc0255.tar.gz
tar -zxvf EtherpadLite-master-4e5e2f5.tar.gz
tar -zxvf EventBus-master-ac9c0a4.tar.gz
tar -zxvf EventLogging-master-faaad63.tar.gz
tar -zxvf EventSimulator-master-685af0f.tar.gz
tar -zxvf EventStreamConfig-master-24e6bc6.tar.gz
tar -zxvf Expressions-master-138cf23.tar.gz
tar -zxvf ExtJSBase-master-022d5d6.tar.gz
tar -zxvf ExtensionDistributor-master-ef0a958.tar.gz
tar -zxvf ExternalArticles-master-d9b3b4e.tar.gz
tar -zxvf ExternalData-master-c2e8027.tar.gz
tar -zxvf ExternalGuidance-master-d1b2453.tar.gz
tar -zxvf ExternalLinkConfirm-master-1cd6a48.tar.gz
tar -zxvf ExtraLanguageLink-master-4f3983d.tar.gz
tar -zxvf FanBoxes-master-fcc8a4c.tar.gz
tar -zxvf Farmer-master-f5b27ab.tar.gz
tar -zxvf Favorites-master-621a884.tar.gz
tar -zxvf FeaturedFeeds-master-8dd3148.tar.gz
tar -zxvf Figures-master-7c4b7f5.tar.gz
tar -zxvf FileAnnotations-master-b18ffb2.tar.gz
tar -zxvf FileExporter-master-4d600dc.tar.gz
tar -zxvf FileImporter-master-b6f570a.tar.gz
tar -zxvf FileSystemImageServer-master-f1c4eea.tar.gz
tar -zxvf FilterListUsers-master-adab9db.tar.gz
tar -zxvf FilterSpecialPages-master-3bfbbb2.tar.gz
tar -zxvf FixedHeaderTable-master-bfaa598.tar.gz
tar -zxvf FlaggedRevs-master-e2abe38.tar.gz
tar -zxvf FlexDiagrams-master-50d191a.tar.gz
tar -zxvf FlexiSkin-master-c495873.tar.gz
tar -zxvf FlickrAPI-master-f2a22d0.tar.gz
tar -zxvf Flow-master-0a212de.tar.gz
tar -zxvf ForcePreview-master-fc00811.tar.gz
tar -zxvf Form-master-522a77a.tar.gz
tar -zxvf FormWizard-master-569fc94.tar.gz
tar -zxvf FormatDates-master-5af89c8.tar.gz
tar -zxvf Forms-master-0ec6c46.tar.gz
tar -zxvf FundraiserLandingPage-master-28451bc.tar.gz
tar -zxvf FundraisingEmailUnsubscribe-master-b8934b9.tar.gz
tar -zxvf FundraisingTranslateWorkflow-master-6930dd8.tar.gz
tar -zxvf GPGMail-master-0b1a075.tar.gz
tar -zxvf GWToolset-master-7196fb5.tar.gz
tar -zxvf Gadgets-master-e766f9d.tar.gz
tar -zxvf Genealogy-master-f067326.tar.gz
tar -zxvf GenerateMochaConfig-master-efe54dc.tar.gz
tar -zxvf GeoCrumbs-master-8c974b1.tar.gz
tar -zxvf GeoData-master-56bf9dc.tar.gz
tar -zxvf GeoGebra-master-b25600d.tar.gz
tar -zxvf GettingStarted-master-58c05c4.tar.gz
tar -zxvf Git2Pages-master-1d40b65.tar.gz
tar -zxvf GitGadgets-master-992e9d6.tar.gz
tar -zxvf Gitweb-master-91834c3.tar.gz
tar -zxvf GlobalBlocking-master-f2d5f6e.tar.gz
tar -zxvf GlobalCheckUser-master-648afd4.tar.gz
tar -zxvf GlobalContribs-master-70fc7be.tar.gz
tar -zxvf GlobalContributions-master-67ace0d.tar.gz
tar -zxvf GlobalCssJs-master-4f4d945.tar.gz
tar -zxvf GlobalNotice-master-cfcde16.tar.gz
tar -zxvf GlobalPreferences-master-57c6b4b.tar.gz
tar -zxvf GlobalUsage-master-74ae596.tar.gz
tar -zxvf GlobalUserGroups-master-97824cd.tar.gz
tar -zxvf GlobalUserPage-master-7597f8a.tar.gz
tar -zxvf GlobalUserrights-master-78925e6.tar.gz
tar -zxvf GlobalWatchlist-master-bfde88a.tar.gz
tar -zxvf GoToShell-master-e44ecfe.tar.gz
tar -zxvf GoogleAdSense-master-cc091cd.tar.gz
tar -zxvf GoogleAnalyticsMetrics-master-8e030b7.tar.gz
tar -zxvf GoogleAnalyticsTopPages-master-99d09d5.tar.gz
tar -zxvf GoogleAuthenticator-master-70a5522.tar.gz
tar -zxvf GoogleCustomWikiSearch-master-7f429a6.tar.gz
tar -zxvf GoogleDocCreator-master-6b78649.tar.gz
tar -zxvf GoogleDocTag-master-dde7669.tar.gz
tar -zxvf GoogleDocs4MW-master-b917a70.tar.gz
tar -zxvf GoogleGeocode-master-9c84e06.tar.gz
tar -zxvf GoogleLogin-master-4bc4ceb.tar.gz
tar -zxvf GoogleNewsSitemap-master-d2c60df.tar.gz
tar -zxvf GooglePlaces-master-f8f67c7.tar.gz
tar -zxvf GoogleSiteSearch-master-3c3e732.tar.gz
tar -zxvf Graph-master-33ed60b.tar.gz
tar -zxvf GraphQL-master-50cb1b3.tar.gz
tar -zxvf GraphViz-master-aa52b5b.tar.gz
tar -zxvf Gravatar-master-d51d4bf.tar.gz
tar -zxvf GroupWhitelist-master-ba52c11.tar.gz
tar -zxvf GroupsSidebar-master-4920faf.tar.gz
tar -zxvf GrowthExperiments-master-4b03425.tar.gz
tar -zxvf GuidedTour-master-f09f435.tar.gz
tar -zxvf HAWelcome-master-227e60e.tar.gz
tar -zxvf HSTS-master-6c16287.tar.gz
tar -zxvf HTMLPurifier-master-f0d4381.tar.gz
tar -zxvf HTMLTags-master-ed7d604.tar.gz
tar -zxvf HTMLets-master-d231207.tar.gz
tar -zxvf HashTables-master-8f52017.tar.gz
tar -zxvf HeadScript-master-3377daf.tar.gz
tar -zxvf HeaderTabs-master-fda8b1d.tar.gz
tar -zxvf HelpCommons-master-2e2b505.tar.gz
tar -zxvf HelpPages-master-485ac1d.tar.gz
tar -zxvf HidePrefix-master-8002be0.tar.gz
tar -zxvf HierarchyBuilder-master-a5e9e32.tar.gz
tar -zxvf HighlightjsIntegration-master-976b4bf.tar.gz
tar -zxvf HitCounters-master-820c4f0.tar.gz
tar -zxvf HostStats-master-2d17d74.tar.gz
tar -zxvf HoverGallery-master-eee681c.tar.gz
tar -zxvf Hreflang-master-607385f.tar.gz
tar -zxvf Html2Wiki-master-abc787f.tar.gz
tar -zxvf I18nTags-master-6b329c6.tar.gz
tar -zxvf IPInfo-master-e25c22f.tar.gz
tar -zxvf Ids-master-5afbcc3.tar.gz
tar -zxvf IframePage-master-7eeb186.tar.gz
tar -zxvf ImageCompare-master-6c2abd4.tar.gz
tar -zxvf ImageMap-master-1052064.tar.gz
tar -zxvf ImageRating-master-42c769d.tar.gz
tar -zxvf ImageSuggestions-master-e790c55.tar.gz
tar -zxvf ImageTweaks-master-0a0e3cc.tar.gz
tar -zxvf ImapAuthorization-master-da9e1ef.tar.gz
tar -zxvf ImportArticles-master-2000621.tar.gz
tar -zxvf ImportFreeImages-master-b60d8f1.tar.gz
tar -zxvf ImportOfficeFiles-master-93e13d0.tar.gz
tar -zxvf ImportUsers-master-7150303.tar.gz
tar -zxvf Inbox-master-48a8870.tar.gz
tar -zxvf IndexFunction-master-5e7a5a7.tar.gz
tar -zxvf InlineCategorizer-master-bbf3f3a.tar.gz
tar -zxvf InputBox-master-3871f95.tar.gz
tar -zxvf Insider-master-9339079.tar.gz
tar -zxvf InteractiveBlockMessage-master-221b58e.tar.gz
tar -zxvf Interlanguage-master-7518732.tar.gz
tar -zxvf Interwiki-master-1cfcab7.tar.gz
tar -zxvf InterwikiExtracts-master-d28dab1.tar.gz
tar -zxvf InterwikiSorting-master-97381c8.tar.gz
tar -zxvf InviteSignup-master-e3ca8c0.tar.gz
tar -zxvf JSBreadCrumbs-master-a649416.tar.gz
tar -zxvf Josa-master-33772f1.tar.gz
tar -zxvf Json5Config-master-51e41e8.tar.gz
tar -zxvf JsonConfig-master-5cdc2ea.tar.gz
tar -zxvf JsonData-master-c42ae07.tar.gz
tar -zxvf Kartographer-master-8648c84.tar.gz
tar -zxvf LDAPAuthentication2-master-7402080.tar.gz
tar -zxvf LDAPAuthorization-master-62afc75.tar.gz
tar -zxvf LDAPGroups-master-a65a4c2.tar.gz
tar -zxvf LDAPProvider-master-4e02428.tar.gz
tar -zxvf LDAPSyncAll-master-a66a3ff.tar.gz
tar -zxvf LDAPUserInfo-master-1e54026.tar.gz
tar -zxvf LabeledSectionTransclusion-master-b53bf48.tar.gz
tar -zxvf LandingCheck-master-071e2df.tar.gz
tar -zxvf LanguageSelector-master-ba32e1c.tar.gz
tar -zxvf LanguageTag-master-cce68df.tar.gz
tar -zxvf LanguageTool-master-a5a1f51.tar.gz
tar -zxvf LastModified-master-c7ab811.tar.gz
tar -zxvf LastUserLogin-master-316e9af.tar.gz
tar -zxvf LdapAuthentication-master-fac0f70.tar.gz
tar -zxvf LegalLogin-master-5ef5cf1.tar.gz
tar -zxvf LibraryCheckout-master-6472282.tar.gz
tar -zxvf Lingo-master-9e6b62e.tar.gz
tar -zxvf LinkFilter-master-1adcf86.tar.gz
tar -zxvf LinkSuggest-master-2b6022d.tar.gz
tar -zxvf LinkSuggest2-master-38132c2.tar.gz
tar -zxvf LinkTarget-master-1e94041.tar.gz
tar -zxvf Link_Attributes-master-5943b83.tar.gz
tar -zxvf LinkedWiki-master-1d78dca.tar.gz
tar -zxvf Linter-master-a52faf1.tar.gz
tar -zxvf LiquidThreads-master-6a3746b.tar.gz
tar -zxvf Listings-master-af8a6ad.tar.gz
tar -zxvf LiveChat-master-e1e4e66.tar.gz
tar -zxvf LiveStreaming-master-9c88f40.tar.gz
tar -zxvf LocalisationUpdate-master-04430ba.tar.gz
tar -zxvf LockAuthor-master-bde65b9.tar.gz
tar -zxvf LockDownEnglishPages-master-1da82a3.tar.gz
tar -zxvf Lockdown-master-f8d5f01.tar.gz
tar -zxvf LogEntry-master-f779cf9.tar.gz
tar -zxvf LoginNotify-master-f1610a3.tar.gz
tar -zxvf LogoFunctions-master-3a78974.tar.gz
tar -zxvf LookupUser-master-2e861ce.tar.gz
tar -zxvf LoopFunctions-master-358ec9a.tar.gz
tar -zxvf Loops-master-085314f.tar.gz
tar -zxvf MP3MediaHandler-master-47c890d.tar.gz
tar -zxvf MWVersionInfo-master-5eb11ea.tar.gz
tar -zxvf MachineVision-master-8d154d6.tar.gz
tar -zxvf MadLib-master-0f9ef15.tar.gz
tar -zxvf MagicNoCache-master-d5c28d6.tar.gz
tar -zxvf MagicNumberedHeadings-master-f4c0dcd.tar.gz
tar -zxvf Mailgun-master-7d49e5d.tar.gz
tar -zxvf Maintenance-master-6e2042f.tar.gz
tar -zxvf MaintenanceShell-master-16180b6.tar.gz
tar -zxvf MapSources-master-6d2b5d5.tar.gz
tar -zxvf MarkAsHelpful-master-777abd4.tar.gz
tar -zxvf MassEditRegex-master-dca9c4d.tar.gz
tar -zxvf MassMessage-master-7c9d015.tar.gz
tar -zxvf MassMessageEmail-master-d53f298.tar.gz
tar -zxvf Math-master-783797b.tar.gz
tar -zxvf MathSearch-master-a3f53cc.tar.gz
tar -zxvf MediaFunctions-master-1ba77c8.tar.gz
tar -zxvf MediaModeration-master-cc8b5eb.tar.gz
tar -zxvf MediaSearch-master-ab8c6f1.tar.gz
tar -zxvf MediaUploader-master-9e505fb.tar.gz
tar -zxvf MediaWikiChat-master-4bfdfe8.tar.gz
tar -zxvf MediaWikiFarm-master-b7b64f1.tar.gz
tar -zxvf Memento-master-f93b39f.tar.gz
tar -zxvf MenuEditor-master-d31aab1.tar.gz
tar -zxvf MergeArticles-master-1e10902.tar.gz
tar -zxvf MessageCommons-master-d9789dd.tar.gz
tar -zxvf MetaMaster-master-4a26f3c.tar.gz
tar -zxvf Metadata-master-d100fc3.tar.gz
tar -zxvf MiniInvite-master-198850d.tar.gz
tar -zxvf MinimumNameLength-master-6e30840.tar.gz
tar -zxvf MintyDocs-master-935a607.tar.gz
tar -zxvf MissedPages-master-2cb2156.tar.gz
tar -zxvf MixedNamespaceSearchSuggestions-master-dbc8b76.tar.gz
tar -zxvf MobileApp-master-c9c44ba.tar.gz
tar -zxvf MobileDetect-master-0f5f119.tar.gz
tar -zxvf MobileFrontend-master-230d13a.tar.gz
tar -zxvf MobileFrontendContentProvider-master-4321fd9.tar.gz
tar -zxvf Model-master-144ef54.tar.gz
tar -zxvf MolHandler-master-3a159aa.tar.gz
tar -zxvf Monstranto-master-e4b9b9a.tar.gz
tar -zxvf MontserratFont-master-fedb189.tar.gz
tar -zxvf Mpdf-master-1c1a5a4.tar.gz
tar -zxvf MsCalendar-master-74c2477.tar.gz
tar -zxvf MsCatSelect-master-e39509e.tar.gz
tar -zxvf MsInsert-master-5d52a7c.tar.gz
tar -zxvf MsLinks-master-7ff0ed2.tar.gz
tar -zxvf MsUpload-master-4e4910f.tar.gz
tar -zxvf MsWikiEditor-master-ef148a8.tar.gz
tar -zxvf MultiBoilerplate-master-46225df.tar.gz
tar -zxvf MultiLanguageManager-master-87aa580.tar.gz
tar -zxvf MultiMail-master-7362690.tar.gz
tar -zxvf MultiMaps-master-d9bb2d4.tar.gz
tar -zxvf MultimediaPlayer-master-7a8a4ca.tar.gz
tar -zxvf MultimediaViewer-master-785352e.tar.gz
tar -zxvf MusicBrainzAuth-master-29cd4c5.tar.gz
tar -zxvf MyVariables-master-a6d90e9.tar.gz
tar -zxvf NCBITaxonomyLookup-master-d2dc57e.tar.gz
tar -zxvf NSFileRepo-master-070d2b7.tar.gz
tar -zxvf NamespaceHTML-master-294ddbf.tar.gz
tar -zxvf NamespacePaths-master-0cda26d.tar.gz
tar -zxvf NamespacePopups-master-631116a.tar.gz
tar -zxvf NamespaceRelations-master-44ed5f2.tar.gz
tar -zxvf NamespaceSidebar-master-3b6ee46.tar.gz
tar -zxvf NativeSvgHandler-master-8544776.tar.gz
tar -zxvf NaturalLanguageList-master-b6daa85.tar.gz
tar -zxvf NavigationTiming-master-a4bd8ac.tar.gz
tar -zxvf NearbyPages-master-a0fd970.tar.gz
tar -zxvf Negref-master-754ff32.tar.gz
tar -zxvf NetworkAuth-master-5c02c62.tar.gz
tar -zxvf NewSignupPage-master-e98606b.tar.gz
tar -zxvf NewUserActions-master-19cddc1.tar.gz
tar -zxvf NewUserMessage-master-440a38f.tar.gz
tar -zxvf NewUserNotif-master-c0df125.tar.gz
tar -zxvf NewestPages-master-3ae69a0.tar.gz
tar -zxvf News-master-27673a3.tar.gz
tar -zxvf NewsBox-master-b565563.tar.gz
tar -zxvf NewsTicker-master-f7bb493.tar.gz
tar -zxvf Newsletter-master-8b91c25.tar.gz
tar -zxvf NoBogusUserpages-master-7a480d0.tar.gz
tar -zxvf NoCat-master-4fa5943.tar.gz
tar -zxvf NoTitle-master-1ed2e6f.tar.gz
tar -zxvf NotebookViewer-master-e9e30cd.tar.gz
tar -zxvf NotesLink-master-09783b1.tar.gz
tar -zxvf Nuke-master-435fb5d.tar.gz
tar -zxvf NukeDPL-master-4506e17.tar.gz
tar -zxvf NumberFormat-master-b7ae02d.tar.gz
tar -zxvf NumberOfWikis-master-e484cbb.tar.gz
tar -zxvf Numbertext-master-6736f54.tar.gz
tar -zxvf NumerAlpha-master-1d85e1a.tar.gz
tar -zxvf OATHAuth-master-33b5f93.tar.gz
tar -zxvf OAuth-master-9f8d4d9.tar.gz
tar -zxvf OAuthAuthentication-master-4f1ef55.tar.gz
tar -zxvf OAuthRateLimiter-master-9f2f28c.tar.gz
tar -zxvf OOJSPlus-master-61dd53b.tar.gz
tar -zxvf OOJsUIAjaxLogin-master-0e9bdbc.tar.gz
tar -zxvf ORES-master-ef425dc.tar.gz
tar -zxvf OdbcDatabase-master-f752834.tar.gz
tar -zxvf OfflineImportLexicon-master-e29e421.tar.gz
tar -zxvf OnionsPorFavor-master-1d981ad.tar.gz
tar -zxvf OnlineStatus-master-c12e43e.tar.gz
tar -zxvf OnlineStatusBar-master-22ed089.tar.gz
tar -zxvf OnlyRecentRecentChanges-master-cd91f13.tar.gz
tar -zxvf OpenBadges-master-b26f91c.tar.gz
tar -zxvf OpenGraphMeta-master-b245d26.tar.gz
tar -zxvf OpenID-master-971d249.tar.gz
tar -zxvf OpenIDConnect-master-3416e02.tar.gz
tar -zxvf OpenJsCad-master-5c426c8.tar.gz
tar -zxvf OpenLayers-master-9b01f16.tar.gz
tar -zxvf OpenStackManager-master-9aaaa7e.tar.gz
tar -zxvf OrphanedTalkPages-master-63d89ff.tar.gz
tar -zxvf OurWorldInData-master-47fe548.tar.gz
tar -zxvf PCRGUIInserts-master-f95ab2b.tar.gz
tar -zxvf PGFTikZ-master-a3f0f52.tar.gz
tar -zxvf PageAssessments-master-80ca7a6.tar.gz
tar -zxvf PageAuthors-master-1a17493.tar.gz
tar -zxvf PageCheckout-master-a450fbc.tar.gz
tar -zxvf PageCreationNotif-master-6e74b07.tar.gz
tar -zxvf PageDisqus-master-41c6cf0.tar.gz
tar -zxvf PageExchange-master-52cc36c.tar.gz
tar -zxvf PageForms-master-1b18d2c.tar.gz
tar -zxvf PageImages-master-fca29f3.tar.gz
tar -zxvf PageInCat-master-9923328.tar.gz
tar -zxvf PageLanguage-master-6ca35b7.tar.gz
tar -zxvf PageMagic-master-aa162eb.tar.gz
tar -zxvf PageNameFormula-master-cb25c88.tar.gz
tar -zxvf PageNotice-master-ec7e625.tar.gz
tar -zxvf PageOwnership-master-a43aefb.tar.gz
tar -zxvf PagePermissions-master-b50bc36.tar.gz
tar -zxvf PagePopups-master-bf36672.tar.gz
tar -zxvf PagePort-master-51a36dd.tar.gz
tar -zxvf PageProperties-master-cab9766.tar.gz
tar -zxvf PageSchemas-master-8b7facf.tar.gz
tar -zxvf PageTools-master-ac8ec62.tar.gz
tar -zxvf PageTriage-master-83b56a8.tar.gz
tar -zxvf PageViewInfo-master-b138bbf.tar.gz
tar -zxvf PagedTiffHandler-master-ee928a9.tar.gz
tar -zxvf PagesList-master-b41ee3b.tar.gz
tar -zxvf PaginateText-master-ca40c1e.tar.gz
tar -zxvf PanScroll-master-271cf2d.tar.gz
tar -zxvf ParentPage-master-9b47665.tar.gz
tar -zxvf ParserFunctions-master-2764c09.tar.gz
tar -zxvf ParserMigration-master-9c040f4.tar.gz
tar -zxvf PasswordlessLogin-master-72626eb.tar.gz
tar -zxvf Patroller-master-d35bdec.tar.gz
tar -zxvf PdfHandler-master-69da294.tar.gz
tar -zxvf PerPageLanguage-master-1ec2b2f.tar.gz
tar -zxvf PerPageLicense-master-4901492.tar.gz
tar -zxvf PerformanceInspector-master-efb8290.tar.gz
tar -zxvf Petition-master-f4d67f4.tar.gz
tar -zxvf PhabTaskGraph-master-cde17d4.tar.gz
tar -zxvf Phonos-master-2d21bc3.tar.gz
tar -zxvf PhotoSwipe-master-1bae94f.tar.gz
tar -zxvf PhpHighlight-master-a57c971.tar.gz
tar -zxvf PhpTags-master-9897d54.tar.gz
tar -zxvf PhpTagsFunctions-master-9ca8656.tar.gz
tar -zxvf PhpTagsMaps-master-0aa8081.tar.gz
tar -zxvf PhpTagsSMW-master-6ac2589.tar.gz
tar -zxvf PhpTagsSPARQL-master-def9d3d.tar.gz
tar -zxvf PhpTagsStorage-master-0680704.tar.gz
tar -zxvf PhpTagsWidgets-master-2f24fa1.tar.gz
tar -zxvf PhpTagsWiki-master-d3e77d4.tar.gz
tar -zxvf PictureGame-master-68b9d89.tar.gz
tar -zxvf PipeEscape-master-4582700.tar.gz
tar -zxvf PluggableAuth-master-2001e8a.tar.gz
tar -zxvf PluggableSSO-master-2263c5b.tar.gz
tar -zxvf Poem-master-c433c06.tar.gz
tar -zxvf Poll-master-f1bc212.tar.gz
tar -zxvf PollNY-master-5f0d18a.tar.gz
tar -zxvf Polyglot-master-c9bc765.tar.gz
tar -zxvf PoolCounter-master-0e15f94.tar.gz
tar -zxvf PopcornEditor-master-15afa94.tar.gz
tar -zxvf PopupAlerts-master-0a80224.tar.gz
tar -zxvf Popups-master-9cb4f45.tar.gz
tar -zxvf PreferencesList-master-dde2560.tar.gz
tar -zxvf Prezi-master-f8029e6.tar.gz
tar -zxvf PrimarySources-master-95358f4.tar.gz
tar -zxvf PrincePDF-master-2a1348b.tar.gz
tar -zxvf PrivateDomains-master-566ce0b.tar.gz
tar -zxvf PronunciationRecording-master-b9e6d95.tar.gz
tar -zxvf ProofreadPage-master-ee092a6.tar.gz
tar -zxvf Prop-master-45f1cd0.tar.gz
tar -zxvf PropertySuggester-master-fd27d10.tar.gz
tar -zxvf ProtectSite-master-283befa.tar.gz
tar -zxvf ProtectionIndicator-master-24a8818.tar.gz
tar -zxvf PurgeClickThrough-master-bf23c77.tar.gz
tar -zxvf Push-master-4737ec3.tar.gz
tar -zxvf PushToWatch-master-72695ad.tar.gz
tar -zxvf PwnedPasswords-master-db0f37c.tar.gz
tar -zxvf Quantcast-master-95584d5.tar.gz
tar -zxvf QuickGV-master-ee05e76.tar.gz
tar -zxvf QuickInstantCommons-master-e109518.tar.gz
tar -zxvf QuickResponse-master-87f29ec.tar.gz
tar -zxvf QuickSearchLookup-master-228e929.tar.gz
tar -zxvf QuickSurveys-master-170d80b.tar.gz
tar -zxvf Quiz-master-d48f149.tar.gz
tar -zxvf QuizGame-master-ec33aec.tar.gz
tar -zxvf RSS-master-1ab96ff.tar.gz
tar -zxvf RT-master-b96cdef.tar.gz
tar -zxvf RandomArea-master-481c86e.tar.gz
tar -zxvf RandomGameUnit-master-85af9ba.tar.gz
tar -zxvf RandomImage-master-bb29709.tar.gz
tar -zxvf RandomImageByCategory-master-0c9ccc5.tar.gz
tar -zxvf RandomInCategory-master-f6f2301.tar.gz
tar -zxvf RandomPages-master-1d0c95a.tar.gz
tar -zxvf RandomSelection-master-7da39c3.tar.gz
tar -zxvf ReadingLists-master-74d5888.tar.gz
tar -zxvf RealMe-master-5b56f6e.tar.gz
tar -zxvf Realnames-master-e6b480c.tar.gz
tar -zxvf ReassignEdits-master-9995e37.tar.gz
tar -zxvf Recoin-master-2bb8597.tar.gz
tar -zxvf RedirectManager-master-2aedf99.tar.gz
tar -zxvf RefreshSpecial-master-6b1f935.tar.gz
tar -zxvf RegexBlock-master-5666619.tar.gz
tar -zxvf RegexFun-master-a57c2af.tar.gz
tar -zxvf RegexFunctions-master-f8992fa.tar.gz
tar -zxvf RegularTooltips-master-82438f7.tar.gz
tar -zxvf RelMicroformat-master-28e3f51.tar.gz
tar -zxvf RelatedArticles-master-1560348.tar.gz
tar -zxvf RelatedSites-master-653da10.tar.gz
tar -zxvf Renameuser-master-972b990.tar.gz
tar -zxvf ReplaceSet-master-9793d79.tar.gz
tar -zxvf ReplaceText-master-8d77ba0.tar.gz
tar -zxvf Report-master-4c7e3c4.tar.gz
tar -zxvf RevisionCommentSupplement-master-40e9974.tar.gz
tar -zxvf RevisionSlider-master-d1be664.tar.gz
tar -zxvf RightFunctions-master-69c64fd.tar.gz
tar -zxvf S5SlideShow-master-7be529f.tar.gz
tar -zxvf SSLClientAuthentication-master-3dced0f.tar.gz
tar -zxvf SVGEdit-master-9e5bd7e.tar.gz
tar -zxvf SacredText-master-6840f81.tar.gz
tar -zxvf SafeDelete-master-a802578.tar.gz
tar -zxvf SandboxLink-master-4d9d7fa.tar.gz
tar -zxvf Sarcasm-master-cb0d8fe.tar.gz
tar -zxvf SaveSpinner-master-5ca9a4f.tar.gz
tar -zxvf Score-master-6e793ba.tar.gz
tar -zxvf Screenplay-master-ed484ab.tar.gz
tar -zxvf Scribe-master-56c7b2a.tar.gz
tar -zxvf Scribunto-master-b0cbcff.tar.gz
tar -zxvf ScrollableTables-master-baedc6a.tar.gz
tar -zxvf SearchExtraNS-master-dd0028d.tar.gz
tar -zxvf SearchStats-master-b21fe10.tar.gz
tar -zxvf SearchThumbs-master-8324d63.tar.gz
tar -zxvf SearchVue-master-7816af0.tar.gz
tar -zxvf SectionDisqus-master-8e5ac9b.tar.gz
tar -zxvf SecureAuth-master-a9cd170.tar.gz
tar -zxvf SecureHTML-master-988e32a.tar.gz
tar -zxvf SecureLinkFixer-master-0b37a34.tar.gz
tar -zxvf SecurePoll-master-e832139.tar.gz
tar -zxvf SecureSessions-master-a4ea80c.tar.gz
tar -zxvf SecurityApi-master-24e336d.tar.gz
tar -zxvf SelectCategory-master-50a4bcf.tar.gz
tar -zxvf SelectTag-master-16eaaf2.tar.gz
tar -zxvf SemanticACL-master-3fa0840.tar.gz
tar -zxvf SemanticBundle-master-d9f06c6.tar.gz
tar -zxvf SemanticDependency-master-5e0b167.tar.gz
tar -zxvf SemanticDrilldown-master-eaab54f.tar.gz
tar -zxvf SemanticGenealogy-master-7caa02e.tar.gz
tar -zxvf SemanticImageAnnotator-master-dc00280.tar.gz
tar -zxvf SemanticImageInput-master-888660d.tar.gz
tar -zxvf SemanticInternalObjects-master-d3e10b2.tar.gz
tar -zxvf SemanticPageSeries-master-8c0b5fc.tar.gz
tar -zxvf SemanticRESTAPI-master-15a12bc.tar.gz
tar -zxvf SemanticRating-master-47d79a8.tar.gz
tar -zxvf SemanticSifter-master-5b90496.tar.gz
tar -zxvf SemanticWebBrowser-master-4b1cc77.tar.gz
tar -zxvf SendGrid-master-bb4831c.tar.gz
tar -zxvf Sentry-master-1c315e7.tar.gz
tar -zxvf Share-master-f3f5fff.tar.gz
tar -zxvf SharedHelpPages-master-8f143d3.tar.gz
tar -zxvf Shibboleth-master-97fcba5.tar.gz
tar -zxvf ShortUrl-master-8fbea6f.tar.gz
tar -zxvf ShoutWikiAPI-master-16e45ad.tar.gz
tar -zxvf ShoutWikiAds-master-45f45b9.tar.gz
tar -zxvf ShowMe-master-0200ee2.tar.gz
tar -zxvf ShowRealUsernames-master-4817e9a.tar.gz
tar -zxvf SideBarMenu-master-2f02470.tar.gz
tar -zxvf SidebarDonateBox-master-b78ce42.tar.gz
tar -zxvf SignWritingMediaWikiPlugin-master-e82eac2.tar.gz
tar -zxvf SimilarEditors-master-5ad964b.tar.gz
tar -zxvf SimpleCalendar-master-1e34533.tar.gz
tar -zxvf SimpleChanges-master-d2e29df.tar.gz
tar -zxvf SimpleSAMLphp-master-b6257a0.tar.gz
tar -zxvf SimpleSort-master-c4c9c39.tar.gz
tar -zxvf SiteMatrix-master-f42cc72.tar.gz
tar -zxvf SiteMetrics-master-32dc2f5.tar.gz
tar -zxvf SiteSettings-master-6888314.tar.gz
tar -zxvf SkinPerNamespace-master-db61c7c.tar.gz
tar -zxvf SkinPerPage-master-fb0cd9b.tar.gz
tar -zxvf SlimboxThumbs-master-2175a48.tar.gz
tar -zxvf SmiteSpam-master-1a12d42.tar.gz
tar -zxvf SocialLogin-master-3c66aca.tar.gz
tar -zxvf SocialProfile-master-7fc561a.tar.gz
tar -zxvf Sofa-master-c698bed.tar.gz
tar -zxvf SoftRedirector-master-35c49ed.tar.gz
tar -zxvf SoftwareVersion-master-ab92f45.tar.gz
tar -zxvf SoundManager2Button-master-97cbd53.tar.gz
tar -zxvf SpamBlacklist-master-3e6ff1e.tar.gz
tar -zxvf SpamDiffTool-master-b61b41d.tar.gz
tar -zxvf SpamRegex-master-89022d5.tar.gz
tar -zxvf Spark-master-026931e.tar.gz
tar -zxvf SparkPost-master-e5c217c.tar.gz
tar -zxvf Special404-master-8607349.tar.gz
tar -zxvf SpecialNamespaces-master-dcfac84.tar.gz
tar -zxvf SpellingApi-master-048c6d5.tar.gz
tar -zxvf SpellingDictionary-master-fcdeec4.tar.gz
tar -zxvf SphinxSearch-master-d9fd704.tar.gz
tar -zxvf SplitPrivateWiki-master-0a3bddd.tar.gz
tar -zxvf SportsTeams-master-4f1ec98.tar.gz
tar -zxvf StaffEdits-master-b5f72d3.tar.gz
tar -zxvf StaffPowers-master-31b560b.tar.gz
tar -zxvf StalkerLog-master-0f5bb9f.tar.gz
tar -zxvf StandardDialogs-master-c257664.tar.gz
tar -zxvf StarterWiki-master-ce83eef.tar.gz
tar -zxvf StatCounter-master-26eba4b.tar.gz
tar -zxvf StickToThatLanguage-master-19083ea.tar.gz
tar -zxvf StickyTOC-master-a440475.tar.gz
tar -zxvf StlHandler-master-adbfc04.tar.gz
tar -zxvf StopForumSpam-master-53e0bed.tar.gz
tar -zxvf StringFunctionsEscaped-master-7d060f7.tar.gz
tar -zxvf StructuredNavigation-master-e867392.tar.gz
tar -zxvf SubPageList3-master-eac79bc.tar.gz
tar -zxvf SubpageFun-master-0a3cd38.tar.gz
tar -zxvf SubpageSortkey-master-e67230d.tar.gz
tar -zxvf Sudo-master-a23f406.tar.gz
tar -zxvf Survey-master-62c0fcb.tar.gz
tar -zxvf SwiftMailer-master-6e56ea7.tar.gz
tar -zxvf SyntaxHighlight_GeSHi-master-91f7fc1.tar.gz
tar -zxvf TEI-master-42a7823.tar.gz
tar -zxvf Tabber-master-4aa0cb6.tar.gz
tar -zxvf Tabs-master-86d9754.tar.gz
tar -zxvf TemplateData-master-28c1471.tar.gz
tar -zxvf TemplateSandbox-master-595122b.tar.gz
tar -zxvf TemplateStyles-master-38aaa56.tar.gz
tar -zxvf TemplateWizard-master-2c47921.tar.gz
tar -zxvf TestLanguageNameGrammar-master-c1468ad.tar.gz
tar -zxvf TextExtracts-master-79756fd.tar.gz
tar -zxvf TextScroller-master-3e3c061.tar.gz
tar -zxvf Thanks-master-f128128.tar.gz
tar -zxvf TheWikipediaLibrary-master-e174b6d.tar.gz
tar -zxvf Theme-master-a7c2771.tar.gz
tar -zxvf ThrottleOverride-master-7b048c7.tar.gz
tar -zxvf TimeMachine-master-c3b4174.tar.gz
tar -zxvf TimedMediaHandler-master-346752a.tar.gz
tar -zxvf TimelineTable-master-bb9f771.tar.gz
tar -zxvf TinyMCE-master-969cbbc.tar.gz
tar -zxvf TitleBlacklist-master-21964ef.tar.gz
tar -zxvf TitleIcon-master-5716fda.tar.gz
tar -zxvf TitleKey-master-6be6178.tar.gz
tar -zxvf TocTree-master-2345480.tar.gz
tar -zxvf Toolhub-master-b711e59.tar.gz
tar -zxvf Tooltip-master-7e31c78.tar.gz
tar -zxvf TopTenPages-master-385c889.tar.gz
tar -zxvf TorBlock-master-9af4537.tar.gz
tar -zxvf Translate-master-4b61c9d.tar.gz
tar -zxvf TranslateSvg-master-01e3eb4.tar.gz
tar -zxvf TranslationNotifications-master-bdb79c5.tar.gz
tar -zxvf TrustedXFF-master-a2c6e18.tar.gz
tar -zxvf TuleapIntegration-master-d89becb.tar.gz
tar -zxvf TuleapWikiFarm-master-eb878a9.tar.gz
tar -zxvf TweetANew-master-26403f6.tar.gz
tar -zxvf TwitterCards-master-9aa6d8d.tar.gz
tar -zxvf TwitterLogin-master-6ada565.tar.gz
tar -zxvf TwitterTag-master-8273387.tar.gz
tar -zxvf TwnMainPage-master-a1fe17b.tar.gz
tar -zxvf TwoColConflict-master-cf8526a.tar.gz
tar -zxvf UIFeedback-master-5235761.tar.gz
tar -zxvf UILangCode-master-fd0a67f.tar.gz
tar -zxvf UnCaptcha-master-513fed6.tar.gz
tar -zxvf UnicodeConverter-master-f715f9b.tar.gz
tar -zxvf UnifiedTaskOverview-master-39ea590.tar.gz
tar -zxvf UniversalLanguageSelector-master-a26b071.tar.gz
tar -zxvf UnlinkedWikibase-master-6bab65c.tar.gz
tar -zxvf UnusedRedirects-master-f74e0a1.tar.gz
tar -zxvf UpdateMediaWiki-master-fb158c5.tar.gz
tar -zxvf UploadBlacklist-master-013fb21.tar.gz
tar -zxvf UploadWizard-master-4193cb1.tar.gz
tar -zxvf UploadsLink-master-33064d8.tar.gz
tar -zxvf UrlGetParameters-master-f53f580.tar.gz
tar -zxvf UrlShortener-master-3063450.tar.gz
tar -zxvf UseResource-master-7f84c38.tar.gz
tar -zxvf UserAgreement-master-e9628fa.tar.gz
tar -zxvf UserExport-master-1b40e37.tar.gz
tar -zxvf UserFunctions-master-afbb36e.tar.gz
tar -zxvf UserGroups-master-1774b73.tar.gz
tar -zxvf UserMerge-master-581898b.tar.gz
tar -zxvf UserOptionStats-master-008eaf7.tar.gz
tar -zxvf UserPageEditProtection-master-1cbdc7a.tar.gz
tar -zxvf UserPageViewTracker-master-97db30b.tar.gz
tar -zxvf UserProtect-master-0700a06.tar.gz
tar -zxvf UserStatus-master-e691989.tar.gz
tar -zxvf UserThrottle-master-56f7918.tar.gz
tar -zxvf VEForAll-master-bf8aecc.tar.gz
tar -zxvf VIKI-master-4702b6c.tar.gz
tar -zxvf Variables-master-9881c17.tar.gz
tar -zxvf VersionCompare-master-e7cbedd.tar.gz
tar -zxvf Video-master-06b11ed.tar.gz
tar -zxvf Views-master-e700c87.tar.gz
tar -zxvf VikiSemanticTitle-master-1def213.tar.gz
tar -zxvf VikiTitleIcon-master-3550641.tar.gz
tar -zxvf VipsScaler-master-9cdab3c.tar.gz
tar -zxvf VisualEditor-master-45f3774.tar.gz
tar -zxvf VoteNY-master-d8d52a5.tar.gz
tar -zxvf VueTest-master-dda7c72.tar.gz
tar -zxvf WSOAuth-master-4e38c6c.tar.gz
tar -zxvf WantedPagesFromNS-master-4070aa0.tar.gz
tar -zxvf WatchAnalytics-master-4b2a130.tar.gz
tar -zxvf WatchSubpages-master-3d3e164.tar.gz
tar -zxvf WebAuthn-master-341f3ae.tar.gz
tar -zxvf WebChat-master-896cdb5.tar.gz
tar -zxvf WebDAV-master-ca28b37.tar.gz
tar -zxvf WebDAVClientIntegration-master-6061851.tar.gz
tar -zxvf WebDAVMinorSave-master-162e482.tar.gz
tar -zxvf WebToolsManager-master-d397bb0.tar.gz
tar -zxvf WhiteSpace-master-10eb033.tar.gz
tar -zxvf WhitelistPages-master-23dc3f1.tar.gz
tar -zxvf WhoIsWatching-master-e768b25.tar.gz
tar -zxvf Whoops-master-dc34bb2.tar.gz
tar -zxvf WhosOnline-master-c910d0e.tar.gz
tar -zxvf Widgets-master-89240d5.tar.gz
tar -zxvf Wigo3-master-d443b5d.tar.gz
tar -zxvf WikEdDiff-master-9c77ec4.tar.gz
tar -zxvf WikiArticleFeeds-master-0fd7c50.tar.gz
tar -zxvf WikiCategoryTagCloud-master-4ef5253.tar.gz
tar -zxvf WikiEditor-master-e57eac9.tar.gz
tar -zxvf WikiForum-master-5e65e5f.tar.gz
tar -zxvf WikiLambda-master-fbfb803.tar.gz
tar -zxvf WikiLexicalData-master-633e7fb.tar.gz
tar -zxvf WikiLove-master-efe035a.tar.gz
tar -zxvf WikiLovesMonuments-master-299735f.tar.gz
tar -zxvf WikiSEO-master-f6fe791.tar.gz
tar -zxvf WikiShare-master-e1fc3a3.tar.gz
tar -zxvf WikiTextLoggedInOut-master-8bf9d8e.tar.gz
tar -zxvf WikiToLDAP-master-f712109.tar.gz
tar -zxvf WikiVideos-master-765a8ef.tar.gz
tar -zxvf Wikibase-master-a856c41.tar.gz
tar -zxvf WikibaseCirrusSearch-master-8f4f761.tar.gz
tar -zxvf WikibaseLexeme-master-bfb058e.tar.gz
tar -zxvf WikibaseLexemeCirrusSearch-master-e36442a.tar.gz
tar -zxvf WikibaseManifest-master-cd85a36.tar.gz
tar -zxvf WikibaseMediaInfo-master-4a094cd.tar.gz
tar -zxvf WikibaseQualityConstraints-master-83d0b8d.tar.gz
tar -zxvf WikibaseStatementUpdater-master-57c4887.tar.gz
tar -zxvf Wikidata.org-master-a4d65bb.tar.gz
tar -zxvf WikidataPageBanner-master-1a02b28.tar.gz
tar -zxvf WikimediaApiPortalOAuth-master-231d54e.tar.gz
tar -zxvf WikimediaBadges-master-86685d3.tar.gz
tar -zxvf WikimediaEditorTasks-master-a2bd4fb.tar.gz
tar -zxvf WikimediaEvents-master-1507fb6.tar.gz
tar -zxvf WikimediaIncubator-master-f31b225.tar.gz
tar -zxvf WikimediaMaintenance-master-0394183.tar.gz
tar -zxvf WikimediaMessages-master-ff39b05.tar.gz
tar -zxvf Wikisource-master-2d302d4.tar.gz
tar -zxvf Wikispeech-master-160c50e.tar.gz
tar -zxvf WikispeechSpeechDataCollector-master-deb4782.tar.gz
tar -zxvf Wikistories-master-59caf0c.tar.gz
tar -zxvf WindowsAzureStorage-master-e906c49.tar.gz
tar -zxvf Workflows-master-bd50256.tar.gz
tar -zxvf XAnalytics-master-772470a.tar.gz
tar -zxvf XSL-master-7113e10.tar.gz
tar -zxvf XenForoAuth-master-86fbca3.tar.gz
tar -zxvf YetAnotherKeywords-master-ab1d8d5.tar.gz
tar -zxvf YotpoReviews-master-c5cfd4d.tar.gz
tar -zxvf YouTube-master-5e96d28.tar.gz
tar -zxvf ZoomableImages-master-0eb871f.tar.gz
tar -zxvf cldr-master-12b9aa8.tar.gz
tar -zxvf examples-master-f742cd9.tar.gz
tar -zxvf googleAnalytics-master-1fb645e.tar.gz
tar -zxvf intersection-master-d2c844f.tar.gz
tar -zxvf timeline-master-289fae4.tar.gz
tar -zxvf wikihiero-master-2fca9e6.tar.gz
