
sudo unar -d -f AdaptiveThumb-master.zip
sudo unar -d -f AddBodyClass-master.zip
sudo unar -d -f AgeParse-master.zip
sudo unar -d -f Amp-master.zip
sudo unar -d -f Attachments-master.zip
sudo unar -d -f AuthManagerOAuth-main.zip
sudo unar -d -f AuthWP-main.zip
sudo unar -d -f AutoCreatePage-master.zip
sudo unar -d -f AutoSitemap-master.zip
sudo unar -d -f AutomatedValues-master.zip
sudo unar -d -f BADIPagesCreatedLinks-master.zip
sudo unar -d -f BCmath-master.zip
sudo unar -d -f BannerAds-main.zip
sudo unar -d -f BoilerRoom-master.zip
sudo unar -d -f Bootstrap-master.zip
sudo unar -d -f BootstrapComponents-master.zip
sudo unar -d -f BugzillaReports-master.zip
sudo unar -d -f CategoryControl2-main.zip
sudo unar -d -f CategoryToolbox-master.zip
sudo unar -d -f Chartie-master.zip
sudo unar -d -f Closures-master.zip
sudo unar -d -f Common-master.zip
sudo unar -d -f CourseEditor-master.zip
sudo unar -d -f CustomHeader-master.zip
sudo unar -d -f CustomLogs-master.zip
sudo unar -d -f CustomSubtitle-master.zip
sudo unar -d -f DSMW-master.zip
sudo unar -d -f DataDump-master.zip
sudo unar -d -f DataValues-master.zip
sudo unar -d -f DataVisualizer-master.zip
sudo unar -d -f Dia-master.zip
sudo unar -d -f DiscordNotifications-master.zip
sudo unar -d -f DiscordRCFeed-main.zip
sudo unar -d -f DiscourseSsoConsumer-main.zip
sudo unar -d -f DocxConverter.zip
sudo unar -d -f Doppelganger-master.zip
sudo unar -d -f DynamicPageList3-master.zip
sudo unar -d -f EUV-master.zip
sudo unar -d -f EmailLogger-main.zip
sudo unar -d -f EmailPage-master.zip
sudo unar -d -f EmailRegistrationFilter-main.zip
sudo unar -d -f EmbedVideo-master.zip
sudo unar -d -f EnhancedReportTime-master.zip
sudo unar -d -f ExcludeRandom-master.zip
sudo unar -d -f ExcludeSubpages-main.zip
sudo unar -d -f Expect-master.zip
sudo unar -d -f ExternalContent-master.zip
sudo unar -d -f ExternalRedirect-master.zip
sudo unar -d -f FacebookComments-master.zip
sudo unar -d -f FacetedCategory-main.zip
sudo unar -d -f Fail2Log-main.zip
sudo unar -d -f FileList-master.zip
sudo unar -d -f FindRefs-master.zip
sudo unar -d -f FlexForm-main.zip
sudo unar -d -f FlexImage-master.zip
sudo unar -d -f FlexiblePrefix-master.zip
sudo unar -d -f FlickrImporter-master.zip
sudo unar -d -f FontAwesome-master.zip
sudo unar -d -f ForceLogin-master.zip
sudo unar -d -f ForceTocOnEveryPage-master.zip
sudo unar -d -f FormInputMik-master.zip
sudo unar -d -f ForumSessionProvider-master.zip
sudo unar -d -f GND-master.zip
sudo unar -d -f GNDShow-master.zip
sudo unar -d -f GbrowseImage-master.zip
sudo unar -d -f GlobalNewFiles-master.zip
sudo unar -d -f GoogleKnowledgeGraph-main.zip
sudo unar -d -f GoogleSiteVerification-master.zip
sudo unar -d -f GroupPortal-master.zip
sudo unar -d -f HTML5Tags-master.zip
sudo unar -d -f HeaderCount-master.zip
sudo unar -d -f HeaderFooter-master.zip
sudo unar -d -f HeaderTree.zip
sudo unar -d -f HidePageTabs-master.zip
sudo unar -d -f HideSection-master.zip
sudo unar -d -f HideSidebar-main.zip
sudo unar -d -f HighlightLinksInCategory-master.zip
sudo unar -d -f Highlightjs_Integration-master.zip
sudo unar -d -f HipchatNotifications-master.zip
sudo unar -d -f HistoryOfPage-master.zip
sudo unar -d -f HtmlFromFile-master.zip
sudo unar -d -f Hypothesis-master.zip
sudo unar -d -f IDProvider-master.zip
sudo unar -d -f IPBAuthLogin-master.zip
sudo unar -d -f ITaskTracker-master.zip
sudo unar -d -f IdGenerator-master.zip
sudo unar -d -f Iframe-master.zip
sudo unar -d -f ImagePagePrintLink-master.zip
sudo unar -d -f ImageSizeInfoFunctions-master.zip
sudo unar -d -f ImagesLoaded-master.zip
sudo unar -d -f ImportDump-master.zip
sudo unar -d -f IncidentReporting-master.zip
sudo unar -d -f Inference-master.zip
sudo unar -d -f InteractiveTimeline-master.zip
sudo unar -d -f Interfaces-master.zip
sudo unar -d -f InterwikiMap-master.zip
sudo unar -d -f InterwikiUsage-master.zip
sudo unar -d -f JIRAConnectorExtension-master.zip
sudo unar -d -f JSWikiGantt-master.zip
sudo unar -d -f JSWikiGanttFrontEnd-master.zip
sudo unar -d -f JobSchEd-master.zip
sudo unar -d -f Jsoner-master.zip
sudo unar -d -f Katsa-master.zip
sudo unar -d -f KeyValueExtension-master.zip
sudo unar -d -f LinkAttributes-master.zip
sudo unar -d -f LinkGuesser-main.zip
sudo unar -d -f LinkTitles-main.zip
sudo unar -d -f LiquidThreadsOverview-master.zip
sudo unar -d -f ListItemFilter-master.zip
sudo unar -d -f LocalS3Repo2-master.zip
sudo unar -d -f LuaCollections-master.zip
sudo unar -d -f LuaLexer-master.zip
sudo unar -d -f MMHandler-master.zip
sudo unar -d -f MW-Avatar-master.zip
sudo unar -d -f MW-OAuth2Client-master.zip
sudo unar -d -f MW-PinyinSort-master.zip
sudo unar -d -f MW-PrettyPhoto-master.zip
sudo unar -d -f MW-QPoll-master.zip
sudo unar -d -f MW-RSS_Publisher-main.zip
sudo unar -d -f MW-RandomImagewithinCommons-main.zip
sudo unar -d -f MW-TitlesAndTargets-master.zip
sudo unar -d -f MWUnit-master.zip
sudo unar -d -f MagnetLinks-master.zip
sudo unar -d -f ManageWiki-master.zip
sudo unar -d -f Maps-master.zip
sudo unar -d -f MasonryMainPage-master.zip
sudo unar -d -f MatchByPrefix-master.zip
sudo unar -d -f MatomoAnalytics-master.zip
sudo unar -d -f MediaWiki-ConsoleOutput-master.zip
sudo unar -d -f MediaWiki-CopyWatchers-master.zip
sudo unar -d -f MediaWiki-Counter-master.zip
sudo unar -d -f MediaWiki-DynamicRedirect-master.zip
sudo unar -d -f MediaWiki-Extension--UserAdmin-master.zip
sudo unar -d -f MediaWiki-Extension-AgeClassification-master.zip
sudo unar -d -f MediaWiki-Extension-DonateButton-master.zip
sudo unar -d -f MediaWiki-Extension-RefreshSiteStatsTable-master.zip
sudo unar -d -f MediaWiki-Extension-SkinCustomiser-master.zip
sudo unar -d -f MediaWiki-Extension-WimaAdvertising-master.zip
sudo unar -d -f MediaWiki-ExtensionStatus-master.zip
sudo unar -d -f MediaWiki-GoogleCodePrettify-master.zip
sudo unar -d -f MediaWiki-RecentChangesOption-master.zip
sudo unar -d -f MediaWiki-TimeConvert-master.zip
sudo unar -d -f MediaWiki-extension-LinkCards-main.zip
sudo unar -d -f MediaWiki-master.zip
sudo unar -d -f MediaWiki-pChart4mw-master.zip
sudo unar -d -f MediaWikiExtensionSummaryRequired-master.zip
sudo unar -d -f MediaWiki_PHPBB_Auth-4.x.zip
sudo unar -d -f Mediawiki-EPSG-main.zip
sudo unar -d -f Mediawiki-Extension-HeaderExtension-master.zip
sudo unar -d -f Mediawiki-Firebase-master.zip
sudo unar -d -f Mediawiki-FlowdockNotify-master.zip
sudo unar -d -f Mediawiki-Model-master.zip
sudo unar -d -f Mediawiki-Opauth-master.zip
sudo unar -d -f Mediawiki-OpauthLogin-master.zip
sudo unar -d -f Mediawiki-Views-master.zip
sudo unar -d -f MediawikiExtension-SimpleFooterLink-main.zip
sudo unar -d -f Mendeley-master.zip
sudo unar -d -f Mermaid-master.zip
sudo unar -d -f MikFunctions-master.zip
sudo unar -d -f MikUML-master.zip
sudo unar -d -f Moca.zip
sudo unar -d -f ModDoc-master.zip
sudo unar -d -f ModernTimeline-master.zip
sudo unar -d -f Mp3Handler-master.zip
sudo unar -d -f MultiCategorySearch.zip
sudo unar -d -f MyTwitter-master.zip
sudo unar -d -f Nagios-master.zip
sudo unar -d -f NamespaceData-master.zip
sudo unar -d -f NamespaceManager-main.zip
sudo unar -d -f Network-master.zip
sudo unar -d -f NewArticleTemplates-master.zip
sudo unar -d -f NewPageCSS-main.zip
sudo unar -d -f NewPageTemplateSelector-main.zip
sudo unar -d -f NewsZ-master.zip
sudo unar -d -f Nfe.zip
sudo unar -d -f NiceCategoryList3-master.zip
sudo unar -d -f OfflineExtension-master.zip
sudo unar -d -f OneColumnAllPages-master.zip
sudo unar -d -f OneColumnAllUsers-master.zip
sudo unar -d -f OttrParserExtension-main.zip
sudo unar -d -f PDFEmbed-main.zip
sudo unar -d -f PDFEmbed-master.zip
sudo unar -d -f PageCrossReference-master.zip
sudo unar -d -f PageEditRestrictions-master.zip
sudo unar -d -f PageImporter-master.zip
sudo unar -d -f PageSync-main.zip
sudo unar -d -f PageViewInfoGA-main.zip
sudo unar -d -f ParentPageLink-master.zip
sudo unar -d -f ParserHooks-master.zip
sudo unar -d -f PdfBook-master.zip
sudo unar -d -f PerformanceMonitor-master.zip
sudo unar -d -f Pickle-master.zip
sudo unar -d -f Piwo-master.zip
sudo unar -d -f PlantUML-master.zip
sudo unar -d -f PlasticMW-master.zip
sudo unar -d -f PluggableSSO-master.zip
sudo unar -d -f Pluso-master.zip
sudo unar -d -f PortableInfobox-master.zip
sudo unar -d -f Preloader-master.zip
sudo unar -d -f PropChainsHelper-master.zip
sudo unar -d -f PubSubHubbubSubscriber-master.zip
sudo unar -d -f PubmedParser-main.zip
sudo unar -d -f Purge-master.zip
sudo unar -d -f PurgePage-master.zip
sudo unar -d -f PushAll-master.zip
sudo unar -d -f QRLite-master.zip
sudo unar -d -f QualityAssuranceMWExtension-master.zip
sudo unar -d -f QueryViz-master.zip
sudo unar -d -f RDFIO-master.zip
sudo unar -d -f ROT13-master.zip
sudo unar -d -f RecentActivity-master.zip
sudo unar -d -f RecordWizard-master.zip
sudo unar -d -f RecurrentEventCalendar-master.zip
sudo unar -d -f RelationLinks-master.zip
sudo unar -d -f RelativePageLinks-master.zip
sudo unar -d -f RemovePII-master.zip
sudo unar -d -f RenderTheFuck-master.zip
sudo unar -d -f RenderThumbnails-master.zip
sudo unar -d -f RottenLinks-master.zip
sudo unar -d -f S5SlideShow-master.zip
sudo unar -d -f SSLClientAuth-master.zip
sudo unar -d -f Sanctions-main.zip
sudo unar -d -f Scopus-master.zip
sudo unar -d -f ScryfallLinks-master.zip
sudo unar -d -f SearchBlox-master.zip
sudo unar -d -f SecureInclude-master.zip
sudo unar -d -f Semantic-Need-master.zip
sudo unar -d -f SemanticActions-master.zip
sudo unar -d -f SemanticApprovedRevs-master.zip
sudo unar -d -f SemanticAuthProfiling-develop.zip
sudo unar -d -f SemanticBreadcrumbLinks-master.zip
sudo unar -d -f SemanticBundle-master.zip
sudo unar -d -f SemanticCite-master.zip
sudo unar -d -f SemanticCompoundQueries-master.zip
sudo unar -d -f SemanticDataImport-master.zip
sudo unar -d -f SemanticDependencyUpdater-master.zip
sudo unar -d -f SemanticDummyEditor-master.zip
sudo unar -d -f SemanticExternalQueryLookup-master.zip
sudo unar -d -f SemanticExtraSpecialProperties-master.zip
sudo unar -d -f SemanticFormsSelect-master.zip
sudo unar -d -f SemanticGlossary-master.zip
sudo unar -d -f SemanticImageAnnotator-master.zip
sudo unar -d -f SemanticImageCaption-master.zip
sudo unar -d -f SemanticInterlanguageLinks-master.zip
sudo unar -d -f SemanticMailMerge-master.zip
sudo unar -d -f SemanticMediaWiki-master.zip
sudo unar -d -f SemanticMetaTags-master.zip
sudo unar -d -f SemanticMustacheFormat-master.zip
sudo unar -d -f SemanticNotifications-master.zip
sudo unar -d -f SemanticOLAP-master.zip
sudo unar -d -f SemanticOrganization-REL1_35.zip
sudo unar -d -f SemanticQueryInterface-master.zip
sudo unar -d -f SemanticResultFormats-master.zip
sudo unar -d -f SemanticScribunto-master.zip
sudo unar -d -f SemanticSignup-master.zip
sudo unar -d -f SemanticStructuredDiscussions-master.zip
sudo unar -d -f SemanticTasks-master.zip
sudo unar -d -f SemanticWatchlist-master.zip
sudo unar -d -f SemanticWikibase-master.zip
sudo unar -d -f Serialization-master.zip
sudo unar -d -f Shariff-Mediawiki-master.zip
sudo unar -d -f Shiny-master.zip
sudo unar -d -f SimpleBatchUpload-master.zip
sudo unar -d -f SimpleBlogPage-master.zip
sudo unar -d -f SimpleMath-master.zip
sudo unar -d -f SimpleMathJax-master.zip
sudo unar -d -f SimpleSkins-master.zip
sudo unar -d -f SimpleTable-master.zip
sudo unar -d -f SimpleTooltip-master.zip
sudo unar -d -f SiteMeterMW-master.zip
sudo unar -d -f SlackNotifications-master.zip
sudo unar -d -f SmartIndex-master.zip
sudo unar -d -f SnapProjectEmbed-main.zip
sudo unar -d -f SocialMediaImage--Mediawiki-Extension--master.zip
sudo unar -d -f Socialcast-PHP-Samples-master.zip
sudo unar -d -f SortChars-master.zip
sudo unar -d -f SourceProtection-master.zip
sudo unar -d -f SparqlCharts-master.zip
sudo unar -d -f SparqlResultFormat-master.zip
sudo unar -d -f Spoilers-master.zip
sudo unar -d -f SpriteSheet-master.zip
sudo unar -d -f StorePdfArticleInAlfresco-master.zip
sudo unar -d -f Streamer-master.zip
sudo unar -d -f Substitutor-master.zip
sudo unar -d -f SummaryCards-master.zip
sudo unar -d -f SwaggerDoc-master.zip
sudo unar -d -f Sync-master.zip
sudo unar -d -f SyntaxHighlightPages-master.zip
sudo unar -d -f SyntaxHighlightThemes-main.zip
sudo unar -d -f SyntaxHighlighter-master.zip
sudo unar -d -f TalkRight-master.zip
sudo unar -d -f TemplateEdit-master.zip
sudo unar -d -f TemplateRest-master.zip
sudo unar -d -f TemplateTableReloaded-master.zip
sudo unar -d -f Testimonials-master.zip
sudo unar -d -f ThumbParser-master.zip
sudo unar -d -f TikaAllTheFiles-main.zip
sudo unar -d -f TimedNotify-master.zip
sudo unar -d -f TimelineStats-master.zip
sudo unar -d -f TimezoneConverter-master.zip
sudo unar -d -f TopLink-main.zip
sudo unar -d -f TranslateWiki-master.zip
sudo unar -d -f TreeAndMenu-master.zip
sudo unar -d -f UndeleteBatch-master.zip
sudo unar -d -f UnifiedExtensionForFemiwiki-main.zip
sudo unar -d -f UniversalSuggester-master.zip
sudo unar -d -f Upload2Commons-master.zip
sudo unar -d -f UploadFields-master.zip
sudo unar -d -f UserHistory-master.zip
sudo unar -d -f UsersWatchlist-master.zip
sudo unar -d -f Validator-master.zip
sudo unar -d -f VariablesLua-master.zip
sudo unar -d -f VectorUp-master.zip
sudo unar -d -f ViewTable-master.zip
sudo unar -d -f ViewWikitext-master.zip
sudo unar -d -f VoiceCommander-master.zip
sudo unar -d -f WSStats-master.zip
sudo unar -d -f WatchGroup-master.zip
sudo unar -d -f WhatsNearby-master.zip
sudo unar -d -f Wiki2Ban-master.zip
sudo unar -d -f WikiBanHammer-master.zip
sudo unar -d -f WikiBanner-master.zip
sudo unar -d -f WikiDiscover-master.zip
sudo unar -d -f WikiMarkdown-main.zip
sudo unar -d -f WikiRatingExtension-master.zip
sudo unar -d -f WikiSearch-master.zip
sudo unar -d -f WikiSearchFront-master.zip
sudo unar -d -f WikibaseDataModel-master.zip
sudo unar -d -f WikibaseEdtf-master.zip
sudo unar -d -f WikibaseExport-master.zip
sudo unar -d -f WikibaseImport-master.zip
sudo unar -d -f WikibaseLocalMedia-master.zip
sudo unar -d -f WikibaseRDF-master.zip
sudo unar -d -f WikidataShow-master.zip
sudo unar -d -f Wikilog-master.zip
sudo unar -d -f Wikimedia-SimpleRadiusAuth-master.zip
sudo unar -d -f Wiretap-master.zip
sudo unar -d -f YAML-master.zip
sudo unar -d -f YandexSiteVerification-master.zip
sudo unar -d -f YetAnotherKeywords-master.zip
sudo unar -d -f ZWIMaker-main.zip
sudo unar -d -f advancedbacklinks-master.zip
sudo unar -d -f ajaxcomments-master.zip
sudo unar -d -f app-dev.zip
sudo unar -d -f cbp-transcription-desk-master.zip
sudo unar -d -f characterescapes-master.zip
sudo unar -d -f collaborationgraph-master.zip
sudo unar -d -f cookiecutter-mediawiki-extension-master.zip
sudo unar -d -f data-values-value-view-master.zip
sudo unar -d -f diagrams-extension-master.zip
sudo unar -d -f externbib-master.zip
sudo unar -d -f financial-maths-mediawiki-master.zip
sudo unar -d -f gchart4mw-master.zip
sudo unar -d -f gliffy-master.zip
sudo unar -d -f highslidegallery-master.zip
sudo unar -d -f hulab_wiki-extensions-master.zip
sudo unar -d -f iann-widget-for-mediawiki-master.zip
sudo unar -d -f issueTracker2-master.zip
sudo unar -d -f javascriptslideshow-master.zip
sudo unar -d -f jehovahsays-master.zip
sudo unar -d -f jhilbert-master.zip
sudo unar -d -f lscache_mediawiki-master.zip
sudo unar -d -f markimages-master.zip
sudo unar -d -f matomo-mediawiki-extension-master.zip
sudo unar -d -f mediawiki-Extension-SpecialUserScore-master.zip
sudo unar -d -f mediawiki-GTag-master.zip
sudo unar -d -f mediawiki-GetPageInfo-master.zip
sudo unar -d -f mediawiki-GoogleRichCards-master.zip
sudo unar -d -f mediawiki-LdapAuth-master.zip
sudo unar -d -f mediawiki-ListTransclusions-master.zip
sudo unar -d -f mediawiki-MediaWikiAuth-master.zip
sudo unar -d -f mediawiki-OurWorldInDataMirror-main.zip
sudo unar -d -f mediawiki-RecentChangesLogFilter-master.zip
sudo unar -d -f mediawiki-ShoogleTweet-master.zip
sudo unar -d -f mediawiki-SubpageWatchlist-master.zip
sudo unar -d -f mediawiki-ViewProtect-master.zip
sudo unar -d -f mediawiki-antispam-master.zip
sudo unar -d -f mediawiki-aws-s3-master.zip
sudo unar -d -f mediawiki-coorconv-master.zip
sudo unar -d -f mediawiki-email-login-master.zip
sudo unar -d -f mediawiki-emailuser-html-master.zip
sudo unar -d -f mediawiki-embed-spotify-master.zip
sudo unar -d -f mediawiki-extension-DownloadBook-master.zip
sudo unar -d -f mediawiki-extension-JQuerySnowfall-master.zip
sudo unar -d -f mediawiki-extension-JsCalendar-master.zip
sudo unar -d -f mediawiki-extension-Metrica-master.zip
sudo unar -d -f mediawiki-extension-Mustache_i18n-master.zip
sudo unar -d -f mediawiki-extension-Plausible-master.zip
sudo unar -d -f mediawiki-extension-QuickUploadZone-master.zip
sudo unar -d -f mediawiki-extension-VigLink-master.zip
sudo unar -d -f mediawiki-extension-WebP-develop.zip
sudo unar -d -f mediawiki-extension-crowdsec-master.zip
sudo unar -d -f mediawiki-extension-datatables-master.zip
sudo unar -d -f mediawiki-extension-minervamenu-main.zip
sudo unar -d -f mediawiki-extension-uservoice-master.zip
sudo unar -d -f mediawiki-extensions-AcceleratedMobilePages-master.zip
sudo unar -d -f mediawiki-extensions-Ainut-master.zip
sudo unar -d -f mediawiki-extensions-BlueSpiceUpgradeHelper-master.zip
sudo unar -d -f mediawiki-extensions-CBxHandler-master.zip
sudo unar -d -f mediawiki-extensions-DataMaps-main.zip
sudo unar -d -f mediawiki-extensions-DataProvider-master.zip
sudo unar -d -f mediawiki-extensions-DonateBoxInSidebar-master.zip
sudo unar -d -f mediawiki-extensions-DummyFandoomMainpageTags-master.zip
sudo unar -d -f mediawiki-extensions-EditCountNeue-master.zip
sudo unar -d -f mediawiki-extensions-EmbedVideo-master.zip
sudo unar -d -f mediawiki-extensions-FileSystemImageServer-master.zip
sudo unar -d -f mediawiki-extensions-GetUserName-master.zip
sudo unar -d -f mediawiki-extensions-Info-master.zip
sudo unar -d -f mediawiki-extensions-LightGallery-master.zip
sudo unar -d -f mediawiki-extensions-ListDuplicateUsers-master.zip
sudo unar -d -f mediawiki-extensions-MetaDescriptionTag-master.zip
sudo unar -d -f mediawiki-extensions-MultiPurge-master.zip
sudo unar -d -f mediawiki-extensions-NewDuplicateUserMessage-master.zip
sudo unar -d -f mediawiki-extensions-PWA-main.zip
sudo unar -d -f mediawiki-extensions-PlaceNewSection-master.zip
sudo unar -d -f mediawiki-extensions-SaferHTMLTag-master.zip
sudo unar -d -f mediawiki-extensions-SaneCase-master.zip
sudo unar -d -f mediawiki-extensions-Settings-master.zip
sudo unar -d -f mediawiki-extensions-ShortDescription-master.zip
sudo unar -d -f mediawiki-extensions-Slides-main.zip
sudo unar -d -f mediawiki-extensions-StubUserWikiAuth-master.zip
sudo unar -d -f mediawiki-extensions-TabberNeue-main.zip
sudo unar -d -f mediawiki-extensions-TemplateStylesExtender-master.zip
sudo unar -d -f mediawiki-extensions-UserLoginLog-master.zip
sudo unar -d -f mediawiki-extensions-YouTrackTicket-master.zip
sudo unar -d -f mediawiki-extensions-cloudflare-master.zip
sudo unar -d -f mediawiki-extensions-ditaa-master.zip
sudo unar -d -f mediawiki-extensions-magicallinkers-master.zip
sudo unar -d -f mediawiki-extensions-wikioutliner-master.zip
sudo unar -d -f mediawiki-github-commit-master.zip
sudo unar -d -f mediawiki-gittip-widget-master.zip
sudo unar -d -f mediawiki-iframe-master.zip
sudo unar -d -f mediawiki-internalwhitelist-master.zip
sudo unar -d -f mediawiki-language-code-master.zip
sudo unar -d -f mediawiki-lazyload-master.zip
sudo unar -d -f mediawiki-linebreaks-extension-master.zip
sudo unar -d -f mediawiki-link-to-archive-master.zip
sudo unar -d -f mediawiki-mail-recentchanges-master.zip
sudo unar -d -f mediawiki-master.zip
sudo unar -d -f mediawiki-mathjax-master.zip
sudo unar -d -f mediawiki-memento-headers-master.zip
sudo unar -d -f mediawiki-moderation-master.zip
sudo unar -d -f mediawiki-movetoskin-master.zip
sudo unar -d -f mediawiki-nagvis-master.zip
sudo unar -d -f mediawiki-nbbc-bbcode-master.zip
sudo unar -d -f mediawiki-numberedheadings-master.zip
sudo unar -d -f mediawiki-page-attachment-master.zip
sudo unar -d -f mediawiki-sections-count-master.zip
sudo unar -d -f mediawiki-shibboleth-authentication-master.zip
sudo unar -d -f mediawiki-special-realname-master.zip
sudo unar -d -f mediawiki-third-party-session-verification-master.zip
sudo unar -d -f mediawiki-uploadconvert-master.zip
sudo unar -d -f mediawikiRemoveRedlinks-master.zip
sudo unar -d -f mediawiki_simple_breadcrumb-master.zip
sudo unar -d -f metaman-master.zip
sudo unar -d -f mpulse-mediawiki-master.zip
sudo unar -d -f mw-Piwigo-main.zip
sudo unar -d -f mw-ScratchBlocks4-master.zip
sudo unar -d -f mw-auth-flarum-main.zip
sudo unar -d -f mw-categorysubscriptions-master.zip
sudo unar -d -f mw-discord-master.zip
sudo unar -d -f mw-editwarning-master.zip
sudo unar -d -f mw-ext-iewarn-master.zip
sudo unar -d -f mw-ext-shorturlapi-master.zip
sudo unar -d -f mw-markdown-master.zip
sudo unar -d -f mw-rtf-main.zip
sudo unar -d -f mw-ses-mailer-master.zip
sudo unar -d -f mw-sse-master.zip
sudo unar -d -f mwExtensionBOFH-master.zip
sudo unar -d -f mwExtensionMantis-master.zip
sudo unar -d -f mwSimpleSamlAuth-master.zip
sudo unar -d -f mwgeshiglue-master.zip
sudo unar -d -f mwpgnjs-master.zip
sudo unar -d -f mwzenphoto-master.zip
sudo unar -d -f namespacepreload-master.zip
sudo unar -d -f nodos-extension-master.zip
sudo unar -d -f pageprotectionplus-master.zip
sudo unar -d -f php-mediawiki-jiki-master.zip
sudo unar -d -f php-namumark-mediawiki-master.zip
sudo unar -d -f pieceofcode-dr-master.zip
sudo unar -d -f ratepage-master.zip
sudo unar -d -f reviews-master.zip
sudo unar -d -f simplefeed-master.zip
sudo unar -d -f skinny-master.zip
sudo unar -d -f storify-widget-for-mediawiki-master.zip
sudo unar -d -f svetovid-master.zip
sudo unar -d -f tweetiki-master.zip
sudo unar -d -f ulogin-MediaWiki-master.zip
sudo unar -d -f wiki-uturn-master.zip
sudo unar -d -f wiki_figma-master.zip
sudo unar -d -f wikistatistics-mediawiki-extension-master.zip
sudo unar -d -f wolfram_cdf-master.zip
sudo unar -d -f wsarrays-master.zip
sudo unar -d -f xglossary-0.1.3.zip
sudo unar -d -f xml2wiki-dr-master.zip
sudo unar -d -f xowa-master.zip
sudo unar -d -f yambe-master.zip
