language: php

services:
  - mysql

jobs:
  fast_finish: true
  include:
    - env: DBTYPE=mysql; MW=1.35.0; SMW=dev-master; TYPE=coverage
      php: 7.4
    - env: DBTYPE=mysql; MW=1.34.0; SMW=3.2.2
      php: 7.4
    - env: DBTYPE=sqlite; MW=1.31.3; SMW=3.0.0
      php: 7.1

install:
  - travis_retry composer self-update
  - bash .travis.install.sh

script: ../phase3/tests/phpunit/phpunit.php -c ../phase3/extensions/ModernTimeline/phpunit.xml.dist

after_success:
  - if [[ "$TYPE" != "coverage" ]]; then exit 0; fi
  - ../phase3/tests/phpunit/phpunit.php -c ../phase3/extensions/ModernTimeline/phpunit.xml.dist --coverage-clover coverage.clover
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

cache:
  directories:
    - $HOME/.composer/cache
