# https://docs.travis-ci.com/user/languages/php
language: php
sudo: required

# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=REL1_27; LOAD_TYPE=legacy
      php: 5.6
    - env: DB=mysql; MW=REL1_31; LOAD_TYPE=legacy
      php: 7.1
    - env: DB=mysql; MW=REL1_32; LOAD_TYPE=extension.json
      php: 7.1
    - env: DB=mysql; MW=REL1_33; LOAD_TYPE=extension.json
      php: 7.2
    - env: DB=mysql; MW=master; LOAD_TYPE=extension.json
      php: 7.1

install:
  - composer install

  # Do this early, not in 'script' section, to kill the build before wasting time
  - composer test

  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-extensions.sh

script:
  - bash ./tests/travis/run-tests.sh

after_script:
  - if [ ls /tmp/stacktrace* 1> /dev/null 2>&1 ] ; then cat /tmp/stacktrace*.log ; fi
  - if [ -f php.log ] ; then cat php.log ; fi
  - if [ -f /tmp/mediawiki-debug.log ] ; then cat /tmp/mediawiki-debug.log ; fi
