language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - originalDirectory=$(pwd)

  - composer self-update
  - cd ..

    # checkout mediawiki
  - wget https://github.com/wikimedia/mediawiki-core/archive/master.tar.gz
  - tar -zxf master.tar.gz
  - rm master.tar.gz
  - mv mediawiki-core-master wiki

  - cd wiki

  - mysql -e 'CREATE DATABASE its_a_mw;'

  - php maintenance/install.php --dbtype mysql --dbuser root --dbname its_a_mw --dbpath $(pwd) --pass nyan TravisWiki admin

  - cd extensions

  - cp -r $originalDirectory PubSubHubbubSubscriber

  - cd PubSubHubbubSubscriber
  - composer install --dev --no-interaction --prefer-source

  - cd ../..

  - echo 'error_reporting(E_ALL| E_STRICT);' >> LocalSettings.php
  - echo 'ini_set("display_errors", 1);' >> LocalSettings.php
  - echo '$wgShowExceptionDetails = true;' >> LocalSettings.php
  - echo '$wgDevelopmentWarnings = true;' >> LocalSettings.php
  - echo '$wgLanguageCode = "en";' >> LocalSettings.php

  - echo '$wgWBClientSettings["siteGlobalID"] = "enwiki";' >> LocalSettings.php

  - echo 'require_once( __DIR__ . "/extensions/PubSubHubbubSubscriber/PubSubHubbubSubscriber.php" );' >> LocalSettings.php

  - php maintenance/update.php --quick

script:
  - cd ../wiki/extensions/PubSubHubbubSubscriber
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_success:
  - php vendor/bin/coveralls -vvv
