language: php

matrix:
  fast_finish: true
  include:
    - env: DBTYPE=sqlite
      php: 5.5
    - env: DBTYPE=mysql
      php: hhvm
    - env: DBTYPE=sqlite
      php: hhvm

before_script:
  - bash ./build/travis/before_script.sh

script:
  - bash ./build/travis/script.sh
