-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: ./sql/abstract/timednotify_pushed_notifications.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE timednotify_pushed_notifications (
  pushed_notification_id VARCHAR(511) NOT NULL,
  pushed_notification_timestamp BIGINT NOT NULL,
  PRIMARY KEY(pushed_notification_id)
);